### ISSUE TITLE
Iteration Plan for March 2019

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2207]
This plan captures our work in **March**. This is a 4 week iteration, and we will **ship** our March Update in **in early April**. We'll continue work we started in the previous iteration, and we started to pick up items from our [roadmap](https://github.com/Microsoft/pai/wiki/Roadmap).

## Endgame
- **March**  ~15~ **20, 2019** Code freeze for the endgame
- ~March 29~ **April 3, 2019** Endgame done

The endgame details for this iteration are tracked in #2307 .

## Plan Items
Below is a summary of the top level plan items.

### Manageability and operation supports
- [x] Detect and alert for unhealthy GPU #2192 @mzmssg @xudifsd 
- [x] Provide the ability to query all the jobs in a Node in PAI Web Portal #2128 @xudifsd
- [x] Team wise storage management support #2204 @ydye @wangdian  

### Better Installation and upgrading experience
- [x] Backward compatible upgrading  #2212 @hao1939 {moved to 0.10.1}

### Usability
- [x] Simplest Job Submission Page for Job (types) that will only run on 1 node #2238 @debuggy @Gerhut 
- [x] Provide filters for jobs list page #302 @Gerhut 
- [x] Refine Job detail page #2211 @sunqinzheng @qfyin 

### Debuggability
- [x] Basic supports for reserving container's life time for debug after job completion #2213 #2214 @ydye 

### Sunset supports
- [x] Remove TensorFlow mpi example #2337 @abuccts 

## Bug Fixes
- [x] hadoop-ai can't detect ECC error #2146 @mzmssg 
- [x] Support nvidia-container-runtime  for gpu isolation #2352  @abuccts 
------------------------------------------
### Pending Items
N/A
------------------------------------------
### Deferred Items - last updated 3/13/2019
- Display resource utility per vc/queue metrics in grafana #2208 @xudifsd 
- Mark utilization for each job in the Node #2250 @xudifsd 
- Instead of setting the GPU/memory/core manually and separately, PAI expose simple SKUs that are available in this PAI instance for user to select #2062 @debuggy @qfyin

**Comment by xudifsd** [comment]
user also request #2208 to be implemented.

**Comment by scarlett2018** [comment]
> user also request #2208 to be implemented.

Thanks @xudifsd , updated.

**Comment by abuccts** [comment]
Add #2232.

**Comment by xwzheng1020** [comment]
Add #2229

**Comment by scarlett2018** [comment]
Adding https://github.com/Microsoft/pai/pull/2337 to the release

**Comment by scarlett2018** [comment]
Adding https://github.com/Microsoft/pai/issues/2146 fix to the release
