### ISSUE TITLE
Job submission v2 with protocol using REST API

### ISSUE THREAD

**Issue by abuccts** [Microsoft/pai#2232]
**What would you like to be added**:

Upgrade to job submission v2 based on protocol yaml.

**Why is this needed**:

To improve job submission user experience and job protocol sharing in marketplace in the near future.

**Without this feature, how does the current module work**:

Use v1 version json config file.

**Components that may involve changes**:

Rest server and webportal.

Work items
-------------
- [x] [Docs] Finalize protocol spec: #2260.
- [x] [Docs] Add new yaml files that follow new protocol:: #2292.
- [x] [Rest Server] Protocol yaml parsing, rendering, and validation: #2274.
- [x] [Rest Server] Convert protocol to framework launcher description file: #2291.
- [x] [Rest Server] Refactor and update rest API v2: #2329.
- [x] [Webportal] Update job submission v2 form: #2461.

**Comment by scarlett2018** [comment]
@yanli2017 - may you help to review the RP #2292 ? @fanyangCS
