### ISSUE TITLE
Need Accurate Job Status, Failure Reason (Category), and useful Resolutions for users to take action

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2326]
Work break down:
- [x] PAI Job Error Spec (Error Type, Error Code, Error Action, etc.) Design #2399 
- [ ] PAI Job Error Spec, Collection and Handling #2483 @yqwang-ms 
   - [x] Spec Table https://github.com/Microsoft/pai/issues/2485: @yqwang-ms 
         1. Setup Initial Spec Config file
   - [x] Launcher https://github.com/Microsoft/pai/issues/2484: @yqwang-ms 
         1. Preserved Known User Container Exit Code
         2. Preserved Unknown User Container Exit Code
         3. Support structured ExitDiagnostics
   - [x] YARN https://github.com/Microsoft/pai/issues/2486: @yqwang-ms 
         1. YARN Collect Runtime Dynamic ExitInfo (Runtime.pai.agg.error)
   - [x] Runtime https://github.com/Microsoft/pai/issues/2487: @mzmssg @xudifsd @Binyang2014 
         1. Refine ExitCode
         2. Split platform log from user log
         3. Generate dynamic ExitInfo into Runtime.pai.agg.error file
   - [x] DiskCleaner https://github.com/Microsoft/pai/issues/2488: @wangdian 
         1. Print User Understandable Container Disk Error Message to DiskCleaner.pai.error file under Container log directory
   - [x] RestServer https://github.com/Microsoft/pai/issues/2489: @Gerhut @sunqinzheng 
         1. Setup and Load Spec
         2. Get more structured ExitInfo from static ExitSpec and dynamic ExitDiagnostics
   - [ ] WebPortal https://github.com/Microsoft/pai/issues/2490  #2456: @Gerhut @sunqinzheng 
         1. Show more structured ExitInfo
         2. Add Error Message and Retry info in UI 
- [ ] Event sevice to provide more detailed failure reasons
- [ ] Refine status based on experiences (test case) _to be itemlized_

=============
Need Accurate Job Status, Failure Reason (Category), and useful Resolutions for users to take action

previous problems are also listed:
- need to know when the job is killed by system (i.e. preempt bonus).
- #824 
- #1832 
- #1819 
- #2022
- #2118 

![image](https://user-images.githubusercontent.com/39592018/54430024-33e9c600-475d-11e9-993c-e7b9b2219182.png)

**Job Status**
- Job Submitted
   **info needed:**
     - _job start time_
     - _retry times_
- Job Waiting 
   **info needed:**
   - _sub task status_: Task queueing; Task allocating resource; Task waiting; 
   - _job waiting time_
- Job Running
   **info needed:**
   - _sub task status_: Task waiting; Task running; Task Completed; Task failed; Task Stopped;
   - _job execution duration_
- Job Stopped
   **info needed:**
   - _job stopped at (time)_
   - _job stopped by (system/user)_
   - _job stopped reason_
- Job Succeeded
   **info needed:**
     - _job end time_
- Job Failed
   **info needed:**
   - _job failed at (time)_
   - _Error Type_
   - _Error Code_
   - _Error Message_
   - _Matched Pattern/resolution_

**Error Type** (this need to be discuss and update after team discussion)
- User Command
- Launcher preparation failure
- Docker failure
- AM and other type (i.e. Error code 177)

**Matched Pattern**
Apply user code analyze rules for user command sub type error.

##Test Cases
**Test Case 1**. An example for resouce not enough "waiting":
“GangAllocation cannot be satisfied in time: Still waiting for 1 outstanding Tasks after timeout 1100s, maybe current available resource for the application is not enough, please retry later.”
![image](https://user-images.githubusercontent.com/39592018/54589846-baeeb500-4a61-11e9-82b3-02379572a3ad.png)

**Test Case 2**.  #2118 
http://*.225:9286/view.html?username=Guisu&jobName=bert-pytorch-corn-18

The job requested 6 GPUs, but the server actually only have 4 as Max.
image
In the application summary log: http://*.225:9286/view.html?username=Scarlett&jobName=scarlett-bert-pytorch-corn-18
[ExitCustomizedDiagnostics]:
onError called into AM from RM due to non-transient error, maybe application is non-compliant.
Exception:
org.apache.hadoop.yarn.exceptions.InvalidResourceRequestException: Invalid resource request, requested GPUs < 0, or requested GPUs > max configured, requestedGPUs=6, maxGPUs=4

**Test Case 3** need to know when the job is killed by system #2333
NNI reports there are some failure jobs, but the status is not clear enough to let them know whether the job is killed by system or failed due to user codes.

**Comment by scarlett2018** [comment]
An example for resouce not enough "waiting":
“GangAllocation cannot be satisfied in time: Still waiting for 1 outstanding Tasks after timeout 1100s, maybe current available resource for the application is not enough, please retry later.”
![image](https://user-images.githubusercontent.com/39592018/54589846-baeeb500-4a61-11e9-82b3-02379572a3ad.png)

**Comment by sterowang** [comment]
How about we display a timeline graph to show this curves together with job status changing?

1. How many containers has been allocated.
2. How many containers pending.
3. How many containers running.
4. How many containers succeeded.
5. How many containers failed.
6. How many containers stopped.

**Comment by yqwang-ms** [comment]
This PR covers latest per container state:
https://github.com/Microsoft/pai/pull/2306/files

For timeline graph, we may need to store status history first.
