### ISSUE TITLE
2019 Mid April Iteration Plan

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/pai#2372]
This plan captures the first half work in **April**. This is a 2 week iteration major focus on User Experience Improvements, and we will **ship** it in the mid of **April**. 
 
We'll continue work we started in the previous iteration, and we started to pick up items from our [roadmap](https://github.com/Microsoft/pai/wiki/Roadmap).

## Endgame
**April 12** Code freeze for the mid April endgame
**April 19** mid April Endgame done
The mid endgame details for this iteration are tracked in #2381.

## Plan Items
Below is a summary of the top level plan items.
- [x] Clone jobs' name is too long to be used #2361 @sunqinzheng 
- [x] Task State in Job Details View #2382 @sunqinzheng 
- [x] rest-server api: submit(create) a job should return the created job #1629 @Gerhut 
- Add TotalGpuCount, TotalTaskCount, TotalTaskRoleCount into job list #2228 
  - [x] REST API @yqwang-ms
  - [x] Webportal  @sunqinzheng 
- [Initial Phase] Need Accurate Job Status, Failure Reason (Category), and useful Resolutions for users to take action #2326
  - [x] Design for PAI Job Error Spec (Error Type, Error Code, Error Action, etc.) Design #2399 @yqwang-ms 
  - [x] Add better error message for Exit code 177 for Job details page #2456 @sunqinzheng 
- [x] Refine Home UI #2513 @sunqinzheng 
- [x] Docker selection guidence in the UX #2518 @yxwithu 

## Bug fixes
- [x] User list ranking is not a-z, z-a. #2016 @Gerhut 
- [x] Job list page: Lag in keyword searchs. #2420 @Gerhut 
- [x] No validation when submitting job by json #2375 @yxwithu 
- [x] [v0.11.0] Job list missing on IE #2515 @Gerhut 
- [x] [IB Drivers] IB drivers' installation will failed on Azure VM. #2470 @ydye 

## Breaking Change
- [x] [Rest API] Add task state; Add job's retry details; Refine job config #2306

## Pending Items
N/A

## Deferred Items - last updated 4/11/2019
- [ ] Job support tags, job list support filter by tag. #2331
- [ ] Confusing status jump: A running Job is converting to "waiting" before converting to "succeeded" #2389 @yqwang-ms 
- [ ] provide detailed reasons for "waiting" jobs #824

**Comment by Gerhut** [comment]
Add issue #2420 , fixed by #2444

**Comment by scarlett2018** [comment]
> Add issue #2420 , fixed by #2444

Updated, thanks @Gerhut!
