### ISSUE TITLE
[Backend]: PAI Job Error Spec, Collection and Handling - Phase II

### ISSUE THREAD

**Issue by yqwang-ms** [Microsoft/pai#2483]
# Goals
1. Assemble, Unify and Enrich PAI Job Error
2. Provide Accurate, Condensed, Structured PAI Job Error for user diagnostic, system analysis, etc
3. Only cover job error after submit to Launcher succeeded.
For error during job submission, it is already covered by RestServer and FL RestAPI Spec:
https://github.com/Microsoft/pai/blob/master/docs/rest-server/API.md
https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/doc/USERMANUAL.md#RestAPI

# Architecture
![image](https://user-images.githubusercontent.com/32826762/56184464-aeec1800-604c-11e9-9991-9c0afdd4888d.png)

# Phase II TODO
- [x] Spec Table https://github.com/Microsoft/pai/issues/2485: @yqwang-ms 
1. Setup Initial Spec Config file for RestServer and Launcher
2. Support ExitSpec Markdown Generator
3. Auto generate ExitSpec Config for RestServer and Launcher
4. Add User Manual Doc for Launcher and PAI Job ExitSpec 

- [x] Launcher https://github.com/Microsoft/pai/issues/2484: @yqwang-ms 
1. Refine Launcher Internal Error Spec, Schema, Lookup and Propagation
2. Separate Framework and Launcher ExitCode
3. Preserved Known User Container Exit Code
4. Preserved Unknown User Container Exit Code
5. Breakdown Framework ExitCode
6. Support structured ExitDiagnostics
7. Fallback to history client to get app report before consider as RMResyncLost
8. Infer TaskStatus to be updated after App completed

- [x] YARN https://github.com/Microsoft/pai/issues/2486: @yqwang-ms 
1. Tune YARN and Launcher Diagnostics Aggregation

- [x] Runtime https://github.com/Microsoft/pai/issues/2487: @mzmssg @xudifsd @Binyang2014 
1. Refine ExitCode
2. Split platform log from user log
3. Generate dynamic ExitInfo into Runtime.pai.agg.error file

- [x] DiskCleaner https://github.com/Microsoft/pai/issues/2488: @wangdian 
1. Print User Understandable Container Disk Error Message to DiskCleaner.pai.error file under Container log directory

- [x] RestServer https://github.com/Microsoft/pai/issues/2489: @Gerhut @sunqinzheng 
1. Setup and Load Spec
2. Get more structured ExitInfo from static ExitSpec and dynamic ExitDiagnostics
