### ISSUE TITLE
Deployments issues on NVIDIA DGX2

### ISSUE THREAD

**Issue by abuccts** [microsoft/pai#2742]
Background
-------------

NVIDIA DGX2 uses a customized [DGX OS](https://docs.nvidia.com/dgx/dgx-os-server-release-notes/index.html) and has GPU drivers, IB drivers, nvidia-docker, etc. installed already. To install PAI on DGX2 server and keep all pre-installed software, there'll be some issues during PAI deployment.

Issues
-------

- [x] Cannot choose a list of services to start (https://github.com/microsoft/pai/issues/2734)
- [ ] Hadoop base image does not contain cuda library (https://github.com/microsoft/pai/issues/2735)
- [ ] Hadoop node manager cannot get GPU status correctly (https://github.com/microsoft/pai/issues/2736)
- [ ] Job exporter cannot get GPU status (https://github.com/microsoft/pai/issues/2737)
- [ ] Cannot listen to InfiniBand or multiple network interfaces (https://github.com/microsoft/pai/issues/2738)
- [x] Cannot start job container by nvidia-docker (https://github.com/microsoft/pai/issues/2739)
- [x] YARN configuration cannot change max resource allocation value dynamically (https://github.com/microsoft/pai/issues/2740)
- [x] Docker and kubelet has many error logs with zfs storage (Docker zfs driver issues)
- [x] Support ed25519 private keys for SSH in deployment (https://github.com/microsoft/pai/pull/3332)

Workaround
--------------

[This branch](https://github.com/microsoft/pai/compare/pai-0.12.y...xiongyf/dgx) based on pai-0.12.y release can be used as a workaround to deploy PAI on DGX2 servers.

**Comment by fanyangCS** [comment]
@abuccts could you provide some links to explain the last issue?

**Comment by abuccts** [comment]
For Docker zfs driver issue, output in `docker info`:

```
Storage Driver: zfs
 Zpool: error while getting pool information strconv.ParseUint: parsing "": invalid syntax
 Zpool Health: not available
 Parent Dataset: storage/docker
 Space Used By Parent: ******
 Space Available: ******
 Parent Quota: no
 Compression: off
```
Here're related issues in [Docker](https://github.com/moby/moby/issues?utf8=%E2%9C%93&q=error+while+getting+pool+information+strconv.ParseUint) and its upstream [Go wrapper for zfs](https://github.com/mistifyio/go-zfs/issues?utf8=%E2%9C%93&q=error+while+getting+pool+information+strconv.ParseUint).

**Comment by fanyangCS** [comment]
closed and track in separate issues.
