### ISSUE TITLE
Protocol V2 release readiness check

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2780]
The item is to record all the area that need to check before formally release protocol V2 in End May release. Any issue founded should be recorded here so that we can easily make go or no-go decisions.

**Check list**
- [x] UX polish and refine
- [x] Job submission experience in web ui, rest api, client (if any)
- [x] Job browsing in job list view, job detail page
- [x] Job information (error status, etc.) experience
- [x] Job V1 and V2 co-exist experience
- [x] Test Cases and CICD
- [x] Documentation for the Protocol, sample, and release note
@abuccts @fanyangCS @sterowang @sunqinzheng @qfyin - please add more.

**Issues**
- [x] Rest server and web portal Dockerfiles didn't use `yarn.lock` (#2768)
- [x] Cannot use <kbd>Backspace</kbd> in paictl (#2769)
- [x] Cannot load vc and login issue in home page (#2774)
- [x] Outdated links for previous submission v2 and marketplace (#2775, #2782)
- [x] Linked job pages from home page didn't work correctly (#2787)
- [x] User management page style issues (#2786)
- [x] Submission v2 and marketplace style issues (#2789)
- [x] Cannot copy and paste url in marketplace directly (#2789)
- [x] Jobs with the same name can be submitted through api v2 (#2837)
- [x] Protocol files in marketplace cannot be used directly (#2827)
- [x] Add extras field in protocol (#2827)
- [x] Do not support responsive mode (#2798, #2805)

**Comment by fanyangCS** [comment]
When submit a job from marketplace, the submit Job v2 should show the selected job from marketplace, instead of setting on the "Upload from local disk"
![image](https://user-images.githubusercontent.com/5820832/57912269-77c38d80-78bc-11e9-9cdd-aff76316c8d3.png)

**Comment by fanyangCS** [comment]
Set the default marketplace view to grid view. Remove "Protocol Preview". Remove the "start" icon for each job. Change the "submit" icon to a better one.
![image](https://user-images.githubusercontent.com/5820832/57912943-1997aa00-78be-11e9-9172-d199ad6eecff.png)

**Comment by fanyangCS** [comment]
when submitting a tensorflow job, I get the error below.
![image](https://user-images.githubusercontent.com/5820832/57914075-8f047a00-78c0-11e9-82ee-edad38a54637.png)

**Comment by fanyangCS** [comment]
the page to change the url of marketplace need a "ok" and a "cancel" button.
![image](https://user-images.githubusercontent.com/5820832/57915163-c4aa6280-78c2-11e9-9c7d-7bcc236d9e9e.png)

**Comment by fanyangCS** [comment]
The field "extras" is not defined in the protocol. 
{
  "protocolVersion": 2,
  "name": "test-nvidia-smi",
  "type": "job",
  "prerequisites": [
    {
      "name": "cntk",
      "protocolVersion": 2,
      "type": "dockerimage",
      "uri": "openpai/pai.example.cntk"
    }
  ],
  "taskRoles": {
    "master": {
      "instances": 1,
      "dockerImage": "cntk",
      "resourcePerInstance": {
        "cpu": 4,
        "memoryMB": 4096,
        "gpu": 3
      },
      "commands": [
        "nvidia-smi"
      ]
    }
  },
  **"extras": {
    "submitFrom": "protocol"
  }**
}

**Comment by fanyangCS** [comment]
in a lower resolution screen. the submission page layout has some issue.
![image](https://user-images.githubusercontent.com/5820832/58023243-ec5b2e00-7b41-11e9-992b-e65ae7f1d98e.png)

**Comment by abuccts** [comment]
Released in [v0.13.0](https://github.com/microsoft/pai/releases/tag/v0.13.0).
