### ISSUE TITLE
June 2019 Release Plan

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#2894]
This plan captures our work in June. This is a 4 week iteration, and we will ship our June Update in in early July. We'll continue work we started in the previous iteration, and we started to pick up items from our [roadmap](https://github.com/Microsoft/pai/wiki/Roadmap).

## Endgame
- **June ~24~ 27** Code freeze for the endgame
- **July ~1st~ TBD** Endgame done

The endgame details for this iteration are tracked in  #2905 

## Plan Items
- [x] Consolidate Job Submission Experience @Binyang2014 @debuggy @sunqinzheng 
   issues: #2621 
   pr: #2867 #2885 #2887
    - [x] @wangdian team wise storage support
- [x] New dedicated VC @mzmssg @sunqinzheng (backend ready)
  issues: #2790  
  ~pr: #2960 #2923 #2921~ 
  - [x] [Dedicated vc] Mapping available gpu nodes to vc #2991
  - [x] doc
- [x] Python SDK and CLI @mydmdm 
  issues: #2808 ~ PR #3018 
- [x] Enable VSCode job protocol v2 support  #2866 @yiyione 
   pr: #2913 
- [x] ~Dockerfile Generator plugin~
- [x] Duration in the Job list should follow the same format as Job details #2972

## Engineering Improvements
- Refine default plugin hosting and code location @abuccts 

## Bug fixes
-  [x] "View job" button on vc page doesn't work as expected #2870
-  [x] Need hidden hint when window width isn't enough for all information #2929

## Deprecated
- Submit job v1
- Marketplace plugin

## Pending Items
- Job submitting wizard
- Replace the "Document" side bar with the "help" icon. #2908
- Hide "0" node GPUs from Available Nodes Chart #2909
- webportal can't show legacy job log #2917

## Deferred 
- [x] AAD and user management #2898 #2897 #1663 @ydye @sunqinzheng
   pr: #2973 #2950 
- - [x] Group management plugin @fenghuajia

**Comment by scarlett2018** [comment]
Released: https://github.com/microsoft/pai/releases/tag/v0.14.0
