### ISSUE TITLE
[Pure K8S] API compatiblity

### ISSUE THREAD

**Issue by sunqinzheng** [microsoft/pai#3206]
To ensure that pai's web portal and clients (vscode, sdk) will work on both YARN based and pure K8S based backend, we need to check the compatibility of current used APIs and implement some new Rest API wrappers for operations based on YARN or HDFS.

## New API requests
- [x] PAI's info API
  - [x] Current version
  - [ ] ~~Endpoints~~
  - [x] Auth method
  - [x] Launcher type
  - [ ] ~~Driver version~~
- [x] Job's stdout / stderr / system log API wrapper
- [ ] ~~Storage API wrapper (HDFS / NFS)~~

## Compatibility
- [ ] Prometheus
  - [x] [Home] Job's gpu usage (abnormal jobs)
  - [x] [Admin - Hardware] hardware utilization queries
  - [x] Alert manager
  - [ ] ~~Home page's `yarn_node_gpu_available` query~~
- [x] Grafana
  - [x] [Dashboard] Dashboard
  - [x] [Job Detail] Job level metrics
  - [x] [Admin - Hardware] Hardware utilization grafana chart
- [x] K8S API
  - [x] [Admin - Service] Pod status
  - [x] [Job Submission] Storage config
- [ ] ~~Exporter API~~
- [ ] Rest API
  - [ ] User, Group
    - [x] [Home, Job Submission] Get user info
    - [x] [Job List] List users
    - [ ] 🕒 User management
    - [ ] 🕒 Group management
  - [ ] Virtual Cluster
    - [x] [Home, Job List] List virtual clusters
      - [x] [Home] Wrong total resources
    - [x] [Home] List node resources
    - [x] 🔧 [Admin - Virtual Cluster] Virtual clusters management #3574 
  - [ ] Auth
     - [ ] 🕒 basic
     - [x] OIDC
       - [x] login
       - [x] logout
  - [ ] Job
    - [x] [Home, Job List] list jobs
      - [ ] ~~[Home] list specific user's job (username query)~~
    - [x] [Job Submission] Submit v2 job
      - [ ] ❓ Can not submit a cpu only job
    - [x] [Home, Job Detail, Job List] Stop job
    - [x] [Job Detail] Get job info
    - [x] [Job Submission, Job Detail] Get job config
    - [ ] ❓ [Job Detail] Get job ssh info
    - [ ] v1 compatibility
      - [ ] ❗️ [Job Clone, Extension] Submit v1 job
    - [ ] ❗️ Exit diagnostics
- [ ] Misc
  - [x] [Job Detail] stdout/stderr log
    - [ ] ❗️ [Mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) issue
  - [x] 🔧 [Job Detail] Job attempts page link #3574 
  - [x] 🔧 [Job Detail] Application tracking page #3574 
  - [x] 🔧 [Admin - Virtual Cluster] Virtual cluster status link #3574

**Comment by fanyangCS** [comment]
closed.
