### ISSUE TITLE
August 2019 Release Plan

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#3250]
This plan captures our work in end July and August. (Internal release. https://github.com/microsoft/pai/releases/tag/v0.15.0)

## Endgame
- TBD Code freeze for the endgame
- TBD Endgame done

The endgame details for this iteration are tracked in  _ticket to be created_.

## Plan Items
Expect: k8s merge. May need more discussion.
- [x] Conduct user interviews and collect feedbacks @scarlett2018 @rabbit008 @debuggy @hzy46 @yiyione @yangou1988
   - [x] Design a questionnaire or interview template
   - [x] Plan for improvements or new functions based on user feedbacks
      - [x] Job submission docs update (homepage link and ssh) PR: https://github.com/microsoft/pai/pull/3347
- [x] Improve job submission page @Binyang2014 @debuggy @sunqinzheng  
   - [x] Quick wizards or templates for users https://github.com/microsoft/pai/issues/3025 (can be included in user interviews) PR: https://github.com/microsoft/pai/pull/3430
   - [x] Enhance data storage functions @wangdian (can be included in user interviews) #3294 PR: https://github.com/microsoft/pai/pull/3416
- [ ] Design JS SDK to encapsulate current RESTful APIs @yiyione @hzy46 PR: https://github.com/microsoft/pai/pull/3414
   - [ ] Go through current APIs #3401  @yiyione
- [x] Python SDK and Jupyter extension https://github.com/microsoft/pai/issues/3289 @mydmdm @hzy46 PR: https://github.com/microsoft/pai/pull/3418
- [x] AAD related issues: mapping between AAD groups and VCs #3275  @mzmssg 
   - [x] Configuration file
   - [x] RESTful API (optional)
- [x] End-to-End AAD test cases (https://github.com/microsoft/pai/issues/2898) @ydye PR: https://github.com/microsoft/pai/pull/3362
- [x] Existing portal issues @sunqinzheng 
   - [x] Homepage #3045 PR: https://github.com/microsoft/pai/pull/3265
   - [x] User filter https://github.com/microsoft/pai/issues/2970 PR: https://github.com/microsoft/pai/pull/3310
- [ ] RESTful API update @yiyione 
  - [ ] Docs #3497
  - [x] Cluster info api @sunqinzheng #3281 PR: https://github.com/microsoft/pai/pull/3281
- [x] TensorBoard integration @TongboZhang (https://github.com/microsoft/pai/issues/3156, https://github.com/microsoft/pai/issues/2095) PR: https://github.com/microsoft/pai/pull/3257
- [x] Refine current home page @Binyang2014  https://github.com/microsoft/pai/issues/2404 https://github.com/microsoft/pai/pull/2197 PR: https://github.com/microsoft/pai/pull/3411
- [x] A confirm dialog for stop actions. https://github.com/microsoft/pai/issues/2577 @fenghuajia PR: https://github.com/microsoft/pai/pull/3408
- [x] Add a button in job-detail page to get merged stdout&stderr log(https://github.com/microsoft/pai/issues/3246) @Binyang2014 
- [x] VSCode minor issues (https://github.com/microsoft/pai/issues/2706) @yiyione
- [x] Attach commit number when PAI is deployed for testing https://github.com/microsoft/pai/issues/3320 @hzy46 @debuggy  PR: https://github.com/microsoft/pai/pull/3374
- [x] SSH-related issues @hzy46
  - [x] Build SSH-enabled docker images as recommendations https://github.com/microsoft/pai/issues/3355 PR: https://github.com/microsoft/pai/pull/3381
  - [x] Add more information when SSH is disabled https://github.com/microsoft/pai/issues/3356 PR: https://github.com/microsoft/pai/pull/3389

## Bug fixes
- [x]  A Hadoop bug in regex to match docker image name (https://github.com/microsoft/pai/issues/3202) @mzmssg 
- [x] Docker's data-root will lost on Azure Node restart(https://github.com/microsoft/pai/issues/2286) @ydye 

## Candidate Items
- [ ] Mismatch between job attempt and metric(https://github.com/microsoft/pai/issues/2938)
- [ ] Alert for abnormal jobs (including long running and low utilization jobs) #2629 
- [ ] Highlight jobs with low GPU utilization(https://github.com/microsoft/pai/issues/2249)
- [ ] Create initial password for new user (https://github.com/microsoft/pai/issues/3133)
- [ ] Refactor eslint of webportal (https://github.com/microsoft/pai/issues/3235) @debuggy 
- [ ] A page for team storage
- [ ] Refine hardware page to break down per GPU usage(https://github.com/microsoft/pai/issues/3348)

## Deferred 
- [ ] Embedded necessary properties in job configuration
    - [ ] Examples: 1. submission signature 2. submission purpose
- [ ] New Marketplace
- [ ] Data storage management UI
- [ ] AAD Web UI (optional)
- [ ] Add better PyTorch example with "shmMB" in its settings https://github.com/microsoft/pai/issues/3357

**Comment by fanyangCS** [comment]
Do you plan to work on marketplace in this release?

**Comment by scarlett2018** [comment]
> Do you plan to work on marketplace in this release?

not yet, just added it to the "pending items" and let's discuss it in next scrum meeting.

**Comment by fanyangCS** [comment]
TensorBoard integration? @TongboZhang

**Comment by TongboZhang** [comment]
> TensorBoard integration? @TongboZhang

Yes, hope this feature can be included in August release.

**Comment by hzy46** [comment]
> > TensorBoard integration? @TongboZhang
> 
> Yes, hope this feature can be included in August release.

TensorBoard integration is added to plan items. @fanyangCS @TongboZhang

**Comment by fanyangCS** [comment]
A candidate feature in this release. https://github.com/microsoft/pai/issues/2577

**Comment by hzy46** [comment]
> A candidate feature in this release. #2577 @scarlett2018 @hzy46

Added to pending items for futher discussion.

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/2404 another candidate feature @hzy46

**Comment by hzy46** [comment]
> #2404 another candidate feature @hzy46

Added to pending items.

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/3246. another one @hzy46

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/3133. this one also?
