### ISSUE TITLE
Pure K8S Alpha Release Plan

### ISSUE THREAD

**Issue by abuccts** [microsoft/pai#3382]
Alpha release for k8s based PAI
====================

Code complete date: Nov. 12

Plan Items
------------
- [x] RBAC enable K8S + KubeSpray #3757 @ydye (pending end-to-end test)
- [x] HiveD test and fix 
- [x] Front-end changes #3812 @yqwang-ms @abuccts 
- [x] Job history https://github.com/microsoft/pai/pull/3831 @debuggy 
- [x] User profile page #3804 @sunqinzheng 
- [x] Token API  #3774 #3834 #3835 

Deferred
----------
- [ ] Internal storage and database #3813 @hzy46 

Finished
---------
- [x] Service Deployment:
  - Framework controller #3435 
  - Scheduler #3495 
  - Choose service list #3432 
  - Choose launcher type #3528
- [x] Authentication (Azure Active Directory)
  - Login
  - Access control
- [x] Webportal
  - Incompatible task role name; Cannot copy token
  - ❗️❗️ FC will crash if init container exit with error @yqwang-ms (use the private image for INT test first, switching to released FC later)
- [x] ❗️ grafana cannot retrieve job status due to naming convention - #3546
- [x] ❗️ some marketplace jobs broken - #3555
- [x] ❗️ wrong resources calculation  - #3595  @abuccts
- [x] failed to fetch stdout, stderr, and "full log" in job page after the job completes https://github.com/microsoft/pai/issues/3576
- [x] ❗️ Job Error Spec, Collection and Handling - #3428 @Binyang2014 
- [x] ❗️ job shown succeeded even it failed #3556 
- [x]  previous job config needs to add ssh plugin to use ssh - #3596  @wangdian 
- [x]  ❗️ runtime breaks gang scheduling - #3587 @wangdian 
- [x] ❗️❗️  backup plan investigation (K8S scheduler) - #3599 @abuccts @yqwang-ms @fanyangCS
- [x] group in vc management #3458 
- [x] ❗️ log manager needs to be accessed through pylon - #3600 @TongboZhang 
- [x] GPU ID is empty, GPU counts in "Task role table" shows as 0. @abuccts #3642
- [x] "Retry Pending" --> "Waiting" @sunqinzheng 
- [x] Customization support for disable MPI (Default enable MPI), so that user can run elastic jobs.  @wangdian (related PR https://github.com/microsoft/pai/pull/3644)
- [x] Azure blob mount issue @wangdian ; (+ other storage test coverage)
- [x] ❗️  HiveD schedule bug causing GPU not unavailable to use @abuccts @fanyangCS @yqwang-ms
- [x] RESTful API compatibility #3206 
- [x] InfiniBand support
- [x] cannot access grafana via an application gateway (https://github.com/microsoft/pai/issues/3635)
- [x] permanent token 
- [x] hide dashboard in admin mode (https://github.com/microsoft/pai/issues/3685)
- [x] from homepage, click "view" button but no response (https://github.com/microsoft/pai/issues/3686)
- [x] job detail page's task role header changes #3636  #3727  #3840 
- [x] fix virtual cluster list's chart #3730 
- [x] job detail page's clone button should be rendered as a link (could be right clicked and opened in a new tab/window) #3854 
- [x] Task should become stopping status after stop job button is clicked #3868 
- [x] Fix the bug that the job list page's status doesn't change after user clicks the stop button. #3869 

Backlogs
----------
- [ ] k8s version Jenkins
- [ ] choose build images
- [ ] drivers installation
- [ ] 🕒REST API for VC (HiveD @abuccts and default VC @Binyang2014 )
- [ ] 🕒Implement v1 api for jobs

**Comment by mzmssg** [comment]
Details about AAD in #3378.
Besides, I think we need to add deployment about controller and scheduler

**Comment by mzmssg** [comment]
Need replace metrics from hadoop, like:
1. dashboard
![image](https://user-images.githubusercontent.com/11887940/63486354-bda27a00-c4d9-11e9-9bcb-fc3c5ba0a20e.png)
2. hardware
![image](https://user-images.githubusercontent.com/11887940/63486417-05c19c80-c4da-11e9-8323-e2d28c3b3007.png)

**Comment by mzmssg** [comment]
Currently, default taskRole name contains capital letters and underline, which is illegel for k8s.
![image](https://user-images.githubusercontent.com/11887940/63491471-d9ae1780-c4e9-11e9-9967-2e892611ad24.png)

**Comment by wangdian** [comment]
Job keep retry and cannot be stopped.

**Comment by fanyangCS** [comment]
@yqwang-ms can you take a look at the "job keeps retrying" issue?

**Comment by abuccts** [comment]
>> Job keep retry and cannot be stopped.

> @yqwang-ms can you take a look at the "job keeps retrying" issue?

This is caused by someone else's test, not related to the code, the whole bed is down.

**Comment by yqwang-ms** [comment]
All nodes becomes **unknown**, so controller and scheduler in statefulset is down.
I have manually restarted them, but all worker nodes are still down.
Need to investigate why all worker nodes in 15 and 16 beds are down.

**Comment by yqwang-ms** [comment]
Seems kubelet are removed in all worker nodes. (probably caused by someone cleaned the k8s cluster)

Even no kubelet history in 10.151.41.21 (15 bed worker)
```
core@paigcr-a-gpu-1115:~$ sudo docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                      PORTS               NAMES
71a06c62c9d5        hello-world                          "/hello"                 3 months ago        Exited (0) 3 months ago                         quizzical_kare
9882be1aa427        hello-world                          "/hello"                 3 months ago        Exited (0) 3 months ago                         nervous_einstein
b14e8b513c45        openpai.azurecr.io/dls/load_client   "python /load_client…"   6 months ago        Exited (137) 3 months ago                       ecstatic_leavitt
6fd11bd7983e        openpai.azurecr.io/dls/load_client   "python /load_client…"   6 months ago        Exited (137) 3 months ago                       zen_kapitsa
a54f9aa4fa7f        openpai.azurecr.io/dls/load_client   "python /load_client…"   6 months ago        Exited (137) 3 months ago                       agitated_khorana
c2ce59b04a8f        openpai.azurecr.io/dls/load_client   "python /load_client…"   6 months ago        Exited (137) 3 months ago                       jovial_boyd
adfca1e60e7e        openpai.azurecr.io/dls/load_client   "python /load_client…"   6 months ago        Exited (137) 3 months ago                       nostalgic_lovelace
d94900c2a098        openpai.azurecr.io/dls/load_client   "python /load_client…"   11 months ago       Exited (137) 3 months ago                       condescending_swirles
d38a16902aef        openpai.azurecr.io/dls/load_client   "python /load_client…"   11 months ago       Exited (137) 3 months ago                       fervent_dijkstra
0e1991722258        827fd3415f7f                         "/bin/bash"              11 months ago       Exited (0) 11 months ago                        wonderful_heisenberg
0bd2ec5f51dc        827fd3415f7f                         "/bin/bash"              11 months ago       Exited (0) 11 months ago                        dreamy_curran
cc2496d1fdad        827fd3415f7f                         "/bin/bash"              11 months ago       Exited (0) 11 months ago                        optimistic_euler
c5a9ebfc72a5        openpai.azurecr.io/dls/load_client   "python /load_client…"   11 months ago       Exited (137) 3 months ago                       admiring_davinci

```

**Comment by yqwang-ms** [comment]
Synced with Hanyu, seems it is caused by his paictl operations.
Let's redeploy 15 and 16.

**Comment by yqwang-ms** [comment]
15 is recovered.
