### ISSUE TITLE
Job Logging issues

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#3617]
**Organization Name**:

**Short summary about the issue/question**:
- [x] Rename Full log to Stdout+Stderr: Dian #3613
- [x] Rename Go to tracking page to such as Go to all logs folder: Dian #3613
- [x] Barrier produce output but cannot find in task "all logs folder": Dian #3620
- [x] Tee runtime logs to docker/k8s stdout/err for easy debugging: Binyang  -- runtime logs were already in console except user logs. No need to change

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
@yqwang-ms - where will these fixes go? master or the pureK8S branch?

**Comment by yqwang-ms** [comment]
pureK8S, @wangdian to give the status

**Comment by wangdian** [comment]
@scarlett2018 PR #3613 and #3620 have already merged into master.

**Comment by wangdian** [comment]
Tee runtime logs to docker/k8s stdout/err for easy debugging: Binyang 
Confirmed with @Binyang2014, runtime logs were already in console except user logs. No need to change.

**Comment by scarlett2018** [comment]
Thanks @wangdian, I'm closing the issue then.
