### ISSUE TITLE
Pure K8S Beta Release Plan

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#3872]
This is the placeholder for the candidate external release, more plan item will coming later.

## Release Manager
@Binyang2014 

## Endgame
- TBD Code freeze for the endgame
- TBD Endgame done

The endgame details for this iteration are tracked in TBD.

## Plan Items
_Below is a summary of the top level plan items (by priority)._
  - [x] **P00** Deployment should be limited within few hours to at most 1 day in general @ydye #4022
     - [x]  Deployment pre-requisit/benchmark/pre-check list #1893
     - [x]  Clear goal for deployment ready for release 
     - [x]  System requirement
     - [x]  Service dependency
     - [x]  Configurations and default values
  - [x] **P0** Remove framework owner reference for priority class #4131 @abuccts
  - [x] **P0** Default not to create priority class #4131 @abuccts 
  - [x] **P0** tag and commit number Alpha version 0.16.0  - 1 day @ydye/@debuggy 
  - [x] **P0** Finalize protocol - Job UUID #3935 @yqwang-ms #4069 
  - [x] **P0** Security - K8S Dashboard https enabled and login with kubeconfig - 2~3 weeks @Binyang2014  #4025
  - [x] **P0** Security - add REST API for checking node/pod status #3892  @sunqinzheng  1 week
  - [x] **P0** Security - security review items @qfyin #4026
  _initContainer Related_ 
  - [ ] **P0** VS Code Client Support for Beta release @yiyione 2 week
    - [x] job simulation for v2 job #3913
    - [x] team wise storage explorer #3945 PR:#4104
    - [x] Source code auto upload #3989
    - [ ] vscode remote debug for pai job #4097
  - [ ] **P0** Finalize document and help #4023 @scarlett2018 
  - [x] **P0** Finalize UX for beta release  @yangou1988  #4024
  - [x] **P0** Candidate - Grafana Dashboard: https://github.com/microsoft/pai/issues/4020
  - [x] **P0.5:** Support to add Pod Creation http error pattern to errorspec #4125 @yqwang-ms
  - [x] **P0.5:** Watchdog auto delete leak priorityclass #3866 @Binyang2014 
  - [x] **P0.5** Remove yarn version components in k8s version object model - 1-2 weeks @ydye #4027
  - [ ] **P0.5** elastic search alternative option (Azure search or DB search as switchable options)  @hzy46 / @mydmdm #4028 PR: https://github.com/microsoft/pai/pull/4164
  - [x] **P0.5** storage manager constantly restart @Binyang2014  #4081 
  - [x] **P1** Security - Pass secret from job yaml as a secrete and to runtime @abuccts @Binyang2014 
  - [x] **P1** Security - Check ACS Docker Image in initContainer #3572 @Binyang2014 
  - [ ] **P1** Disallow ApiServer HA in beds #4120 @Binyang2014 
  - [x] **P1** Job history dev log on server and clients - 1 day @debuggy 
  - [x] **P1** Replace code injection in webportal with new plugin implementation (~storage and~ set tensorboard disable by default) @Binyang2014 https://github.com/microsoft/pai/pull/4105
  - [x] **P1** do not modify user submitted/cloned job yaml #3823 @debuggy 
  - [ ] **P1** kube runtime may change user's python environment #3941 @abuccts 
  - [x] **P1** Include Pure K8s tests in Jenkins #2455 #2280 @abuccts #4035 #4059 
  - [x] **P2** Remove yarn version components in building k8s version images @ydye  #4167 
  - [x] **P1** Candidate - a failed runtime plugin shouldn't fail the entire runtime #4014 @Binyang2014 
  - [ ] **P2** Security - When cloning a job, if it is pulling docker from ACS and it is cloned by a different user, warn the user to fill in user/password, if it is cloned by the same user, auto-fill the user/password #3829 
  - [x] **P1** Job retry page issue #4008 @debuggy 
  - [x] **P1** GPU Vendor @abuccts #4090 #4093
  - [x]  **P1** For basic authentication mode, prepare document to explain how to create a group and associate users to the group #4130 

## Deploy Notices
  - [ ] **P0** Set and deploy v=2 log level for all k8s components #4123 @Binyang2014 

---------------
**Some features on the [special branch](https://github.com/microsoft/pai/blob/pai-for-edu/docs/pai-for-edu.md)**
- [x] unified storage interface for users
- [x] job persistence: enhanced `codeDir` and `outputDir`
- [x] `ssh` key management and simplifying user behavior of `ssh` plugin
- [ ] open `ssh` connection in browser
- [x] Show ssh command in job detail page
- [x] `etcd` to DB synchronizer - job (basic) / user
- [ ] favorite jobs
---------------
- Grafana metrics link does not have time interval
- Jupyter notebook integration in job detail page
- Implement JobEnv and pass user-defined environment variables to runtime (Binyang https://github.com/microsoft/pai/issues/3956)
- Skip intra communication for elastic job (Binyang https://github.com/microsoft/pai/issues/3708)
- Bring back debug mode (Binyang https://github.com/microsoft/pai/issues/3643, https://github.com/microsoft/pai/issues/2210)
- Support nested AAD group (Yundong, https://github.com/microsoft/pai/issues/3440)
- replace disk cleaner with k8s pod eviction policy (https://github.com/microsoft/pai/issues/3340, https://github.com/microsoft/pai/issues/3765)
- When job is waiting, show the detailed waiting reason somewhere in the job page. (https://github.com/microsoft/pai/issues/3847)
- Archive logs to elastic search
- Add retry count to task and show retry history (https://github.com/microsoft/pai/issues/3938)
- Exec to job containers on webportal
- persist service log (https://github.com/microsoft/pai/issues/2129)
- [ ] improve user group adding to VC experience
- [ ] improve HiveD configuration experience
- [ ] Show job priority in webportal
- [ ] introduce a new job state "initialization"  (https://github.com/microsoft/pai/issues/4141)
- [x] Admin home page only showing abnormal jobs, should show my jobs by default

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/issues/4225

**Comment by scarlett2018** [comment]
made an internal release.
