### ISSUE TITLE
P0 - Finalize UX for beta release

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#4024]
as title

**Comment by yangou1988** [comment]
P0
- [ ] Header, left navigation and command bar #4057
- [ ] Homepage (visitor before sign in) #3712
- [ ] Homepage (normal user and admin)
- [ ] WebUI Font Format Adjustment #3877 
------------------------------------------------------
- [ ] Job list page
- [ ] Job Detail
- [ ] Retry
- [ ] Submit job
- [ ] Marketplace
- [ ] Profile
- [ ] Hardware
- [ ] Services
