### ISSUE TITLE
PAI 0.18.0 Release and Endgame Plan

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4225]
This issue contains our release plan for OpenPAI 0.18.0.

## Release Manager
@hzy46

## Endgame

- [x] License (3.20)
- [x] Publish sub repos (3.23, except hivedscheduler)
    - [x] hivedscheduler:  v0.3.2 @yqwang-ms 
    - [x] openpai-protocol: v2.0.0-alpha @abuccts 
    - [x] openpai-runtime: v0.1.0 @Binyang2014 
    - [x] openpaisdk: v0.1.0 @yiyione @mydmdm 
    - [x] openpaimarketplace: v1.2.0 @debuggy 
    - [x] openpaivscode: v0.3.0 @yiyione 
- [x] Remove code (1 ~ 2 days)
    - [x] remove hivedscheduler: PR: https://github.com/microsoft/pai/pull/4319
    - [x] remove protocol: PR https://github.com/microsoft/pai/pull/4307
    - [x] remove runtime: PR https://github.com/microsoft/pai/pull/4311
    - [x] remove openpaivscode: PR https://github.com/microsoft/pai/pull/4317
    - [x] remove openpaisdk
    - [x] remove openpaimarketplace PR: https://github.com/microsoft/pai/pull/4324
- [x]  build process
  - [x] sub repo CI/CD
    - [x] hivedscheduler
    - [x] openpai-protocol
    - [x] openpai-runtime
    - [x] openpaisdk
    - [x] openpaimarketplace
    - [x] openpaivscode
  - [x] sub repo image build
  - [x] OpenPAI build based on sub repo
- [ ] every sub repo has a stable release
    - [x] hivedscheduler
    - [x] openpai-protocol
    - [x] openpai-runtime
    - [ ] openpaisdk
    - [x] openpaimarketplace
    - [x] openpaivscode
- [ ] Code freeze, create release branch (4.17)
- [ ] Endgame done (5.6)

## Plan Items
  - [x] Schema change:
    - [x] Modify `gpuType` to support CPU and GPU
    - <del> Job priority </del>
  - [x] Refine Rest-server API Issue: #4337   PR: #4355
  - [x] upgrade verification @hzy46 issue https://github.com/microsoft/pai/issues/1838
    -  [upgrade doc](https://github.com/microsoft/pai/blob/zhiyuhe/update_doc_0.18.0/docs/upgrade/upgrade_to_v0.18.0.md) in PR https://github.com/microsoft/pai/pull/4238
  - [x] check installation for separate repos @hzy46
    - [x] check dockerd config and exclude from k8s deployment
    - [x] kubespray quick-start make registries configurable
    - [x] kubeconfig copy issue
    - [x] refine error message in hived config generation
    - [x] quick-start change tag to release tag
    - [x] include gcr.io images (k8s dashboard, scheduler) in service image build
    - [x] registry mirrors do not work when pulling service images
    - [x] wait for device plugin until it is ready
    - [x] inform user of pai cluster id, configuration, username, password PR https://github.com/microsoft/pai/pull/4267
    - [x] clean docker image in `service-boot.sh` PR https://github.com/microsoft/pai/pull/4248
    - [x] add FAQs and troubleshooting PR https://github.com/microsoft/pai/pull/4249
  - [x] security review @qfyin 
  - [x] license @qfyin 
  - [x] publish separate repos
    - [x] hivedscheduler @yqwang-ms 
    - [x] openpai-protocol @abuccts 
    - [x] openpai-runtime (ETA by 2/28) @Binyang2014 
    - [x] openpaisdk @yiyione  @mydmdm 
       - [x] publish package to [NPM](https://www.npmjs.com/org/microsoft)
    - [x] openpaimarketplace (ETA by 3/5) @debuggy
       - <del>[ ] cherry-pick synchronizer @hzy46 </del> 
    - [x] openpaivscode @yiyione 
    - [x] openpai-nb @mydmdm @hzy46 
  - [x] apt package cache in kube-runtime @hzy46  issue https://github.com/microsoft/pai/issues/4211 PR https://github.com/microsoft/pai/pull/4226
  - [x] Refactor storage by leveraging persistent volumes @abuccts PR https://github.com/microsoft/pai/pull/4157
   - [x] elastic search alternative option (Azure search or DB search as switchable options)  @hzy46 / @mydmdm #4028 PR: https://github.com/microsoft/pai/pull/4164
  - [x] remove elasticsearch  PR: https://github.com/microsoft/pai/pull/4304

## Documentation
- [ ] Full scan of E2E document, split into small tasks for sub review if needed. @scarlett2018 @hzy46  @mydmdm  #4023 

## BugFix
- [x] Wrong retry log path in job history issue https://github.com/microsoft/pai/issues/4232 PR: https://github.com/microsoft/pai/pull/4237 @debuggy 
- [x] API server overloaded by job detail page when containers are too many https://github.com/microsoft/pai/issues/4263  PR https://github.com/microsoft/pai/pull/4270 https://github.com/microsoft/pai/pull/4279 @yiyione

## Candidate Items
  - [x] Show gpu metrics in Grafana @Binyang2014 
  - [x] hivedscheduler metric @yqwang-ms 
  - [x] experience enhancement of connecting to container (ssh or other way)
    - [x] (at least) concatenate the command e.g. `ssh -i <keyfile> -p <port> root@<ip>` (now user needs to copy port / ip respectively and sometimes forget root) PR https://github.com/microsoft/pai/pull/4250
    - <del> (optional) ssh key management #4094 
    - <del> (optional) connect to container directly from webportal (ssh / exec ..)
  - <del>Provide standard deep learning docker images @hzy46 issue https://github.com/microsoft/pai/issues/4227 </del>
  - [x] unit test for kube-runtime plugins
  - [x] Job API not return correct appLaunchedTime Issue https://github.com/microsoft/pai/issues/4295

**Comment by VitoRazor** [comment]
Hello, thanks for your continuous efforts on openpai, which has helped us a lot.
May I ask if there is a more accurate update of v0.18.0? We can't wait to get it.

**Comment by scarlett2018** [comment]
> Hello, thanks for your continuous efforts on openpai, which has helped us a lot.
> May I ask if there is a more accurate update of v0.18.0? We can't wait to get it.

@VitoRazor - thanks for the comments and supports. we are working on the end game, the release is coming soon in the following week with a clear release note about the updates =).

Would you mind share more info about how your organization is currently using OpenPAI? this will helps to help you better. (feel free to skip questions, the more info you provide, the better we understand your usage. This info is only for OpenPAI to better understand the current users, we will not use this info for other purpose.).

Organization Name:

Short summary about the issue/question:

Brief what process you are following:

How to reproduce it:

OpenPAI Environment:

OpenPAI version:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Others:
Anything else we need to know:
