### ISSUE TITLE
OpenPAI 0.18.0 Endgame Plan

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4315]
release plan https://github.com/microsoft/pai/issues/4225
release manager @hzy46
test period: 4.20~5.6

## New Feature

***Test in AAD mode***:

Feature | Feature Owner | Test Owner(s) | Test case
  - [x] rest-server api | | @yiyione |  *issue placeholder*
  - [x] storage refactor | @abuccts | @Binyang2014 | [#4157](https://github.com/microsoft/pai/pull/4157#issuecomment-617732773)
  - [x] postgres job history | @hzy46  | @debuggy | [test cases](https://github.com/microsoft/pai/pull/4164) 
  - [x] new marketplace | @debuggy | @hzy46 | [test cases](https://github.com/microsoft/openpaimarketplace/issues/20)
  - [x] openpai sdk | @yiyione @mydmdm |  [test cases](https://github.com/microsoft/pai/issues/4412)
  - [x] apt cache in runtime  | @hzy46 | @Binyang2014 | [test cases](https://github.com/microsoft/pai/pull/4226#issuecomment-616390565)
  - [x] hivedscheduler metric | @abuccts   | @debuggy  | [#4329](https://github.com/microsoft/pai/pull/4329#issuecomment-617735363)
  - [x] concat ssh command | @hzy46 | @yiyione | [test cases](https://github.com/microsoft/pai/pull/4250#issuecomment-616393578)
  - [x] correct appLaunchedTime | @abuccts | @Binyang2014 | [#4301](https://github.com/microsoft/pai/pull/4301#issuecomment-617724889)
  - [ ] amd gpu metrics in Grafana | @Binyang2014  | @hzy46 (test this during upgrade) | [test cases](https://github.com/microsoft/pai/pull/4258#issuecomment-617735186)

***Test in basic authentication mode***:
  - [x] installation script change |  @ydye  | @hzy46 | *issue placeholder*
  - [x] rest-server api | | @yiyione |  #4502 
  - [x] storage refactor | @abuccts | @Binyang2014 | [#4157](https://github.com/microsoft/pai/pull/4157#issuecomment-617732773)
  - [x] postgres job history | @hzy46  | @debuggy | [test cases](https://github.com/microsoft/pai/pull/4164) 
  - [x] new marketplace | @debuggy | @hzy46 | [test cases](https://github.com/microsoft/openpaimarketplace/issues/20)
  - [x] openpai sdk | @yiyione @mydmdm |  [test cases](https://github.com/microsoft/pai/issues/4412) #4502 
  - [x] apt cache in runtime  | @hzy46 | @Binyang2014 | [test cases](https://github.com/microsoft/pai/pull/4226#issuecomment-616390565)
  - [x] hivedscheduler metric | @abuccts   | @debuggy  | [#4329](https://github.com/microsoft/pai/pull/4329#issuecomment-617735363)
  - [x] concat ssh command | @hzy46 | @yiyione | [test cases](https://github.com/microsoft/pai/pull/4250#issuecomment-616393578)
  - [x] correct appLaunchedTime | @abuccts | @Binyang2014 | [#4301](https://github.com/microsoft/pai/pull/4301#issuecomment-617724889)

## Prioritized Regression Test
  - [x] Basic Auth
    - [x] user: create admin user/create non-admin user/update information/delete user
      - [x] issue #4489
    - [x] job: submit an example job/view job/view job metrics
    - [x] VCs: set up VCs/grant VC access/submit job to new VCs/revoke VC access
      - [x] issue #4482
    - [x] storage: nfs storage setup/use nfs storage in job
    - [x] admin dashboard: dashboard/service dashboard/hardware dashboard/k8s dashboard
    
## Full Test (as usual)
to be updated

## Other Work Items
  - [x] openpaisdk
  - [x] remove yarn components in pai_build, service object model, jenkins @ydye 
  - [x] remove yarn document in `docs` @abuccts 
  - [x]  E2E document #4023 
    - [x] document writing
    - [x] review #4439
  - [x] release note #4452 
  

## Issues
- [ ] (known issue) marketplace: https://github.com/microsoft/openpaimarketplace/issues/17

**Comment by lbin** [comment]
Hi, when will you create release branch?

**Comment by hzy46** [comment]
> Hi, when will you create release branch?

It has been created: https://github.com/microsoft/pai/tree/pai-0.18.y
