### ISSUE TITLE
[REST API] refine the spec

### ISSUE THREAD

**Issue by mydmdm** [microsoft/pai#4337]
The existing [RESTful API doc](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/microsoft/pai/master/src/rest-server/docs/swagger.yaml#operation/v2createJob) is incomplete and inconsistent with real implementation, thus we need to 

- [ ] refine the rest api spec
    - [x] get /api/v2/info
    - [x] get /api/v2/cluster/skutypes (internal)
    - [x] get /api/v2/token
    - [x] delete /api/v2/token/{token}
    - [x] post /api/v2/token/application
    - [x] change `token` to `tokens` in doc #4389 

    - [x] get /api/v2/authn/oidc/login
    - [x] get /api/v2/authn/oidc/logout
    - [x] post /api/v2/basic/login (**authn/basic/login**??)
    - [ ] /api/v2/basic/logout (?) (yundong)

    - [x] post /api/v2/users
    - [x] get /api/v2/users
    - [x] get /api/v2/users/{user} (coding #4379 , docs are done)
    - [x] put /api/v2/users
    - [x] put /api/v2/users/me
    - [x] get /api/v2/users/{user}
    - [x] delete /api/v2/user/{user}

    - [ ] put /api/v2/user/{user}/group
    - [ ] put /api/v2/user/{user}/grouplist
    - [ ] delete /api/v2/user/{user}/group
    - [ ] change `user` to `users` in doc (put-delete /user/{user}/group)

    - [x] get /api/v2/groups
    - [x] post /api/v2/groups
    - [x] get /api/v2/groups/{group}
    - [x] put /api/v2/groups/{group}
    - [x] delete /api/v2/groups/{group}
    - [x] get /api/v2/groups/{group}/userlist
    - [x] change `group` to `groups` in doc 

    - [x] get /api/v2/virtual-clusters
    - [x] get /api/v2/virtual-clusters/{vc}

    - [x] get /api/v2/storages
    - [x] get /api/v2/storages/{storage}

    - [x] get /api/v2/jobs
    - [x] post /api/v2/jobs (**clarify job name constraint** #4391)
    - [x] get /api/v2/jobs/{user}~{job}
    - [x] get /api/v2/jobs/{user}~{job}/config
    - [x] put /api/v2/jobs/{user}~{job}/exectionType
    - [x] *check* token is checked in all methods not only `post` (yifan)

    - [x] get /api/v2/jobs/{user}~{job}/job-attempts/healthz
    - [x] get /api/v2/jobs/{user}~{job}/job-attempts
    - [x] get /api/v2/jobs/{user}~{job}/job-attempts/{attempt}
    - [x] add authentication to job history APIs (mingliang)

    - [x] get /api/v2/kubernetes/nodes
    - [x] get /api/v2/kubernetes/pods

- [ ] update js-sdk accordingly
    - [ ] classes and clients
    - [ ] tests
