### ISSUE TITLE
OpenPAI SDK 0.1.0 test case

### ISSUE THREAD

**Issue by yiyione** [microsoft/pai#4412]
# Test case for openpai sdk 0.1.0 in PAI 0.18.0

*Please wait for the sdk 0.1.0 ready.* 
Steps: 
1. Install the SDK from NPM
2. Test call rest API.
3. Test CLI.

### Install the SDK form NPM.

  - [x] npm install @microsoft/openpai-js-sdk
  
### Test call rest API:

  - AAD authentication mode:

    api:
    - [x] getClusterInfo

    token:
    - [x] getTokens
    - [x] deleteToken
    - [x] createApplicationToken
    
    authn:
    - [x] oidcLogin
    - [x] oidcLogout
    
    user:
    - [x] getAllUser
    
    group:
    - [x] getAllGroup
    - [x] createGroup
    - [x] updateGroup
    - [x] getGroup
    - [x] deleteGroup
    - [x] getGroupMembers (Fix PR [#4398](https://github.com/microsoft/pai/pull/4398))
    
    virtual cluster:
    - [x] listVirtualClusters (Fix PR [#4465](https://github.com/microsoft/pai/pull/4465))
    - [x] getVirtualCluster
    
    storage:
    - [x] getStorages (Fix PR [#4500](https://github.com/microsoft/pai/pull/4500))
    - [x] getStorage
    
    job:
    - [x] createJob
    - [x] listJobs (Fix PR [#4449](https://github.com/microsoft/pai/pull/4449))
    - [x] getJob
    - [x] getJobConfig
    - [x] updateJobExecutionType
      - [x] update job execution type to STOP
      - [x] update job execution type to START
    
    job history:
    - [x] getJobAttemptsHealthz
    - [x] getJobAttempts (Fix PR [#4460](https://github.com/microsoft/pai/pull/4460) [#4514](https://github.com/microsoft/pai/pull/4514))
    - [x] getJobAttempt
    
    kubernetes:
    - [x] getK8sNodes
    - [x] getK8sPods

  - Basic authentication mode:

    authn:
    - basicLogin
      - [x] login with correct username and password
      - [x] login with non-existent username
      - [x] login with incorrect password
    - basicLogout
      - [x] logout with correct token
      - [x] logout with incorrect token

    user:
    - createUser
      - [x] Create a user
      - [x] Create a conflict user
      - [x] Create a user by application token
      - [x] Create a user by non-admin user token
    - updateUser
      - [x] Update a user
        - [x] Update a user, patch: true
        - [x] Update a user, patch: false
      - [x] Update a non-existent user
      - [x] Update a user by application token
      - [x] Update a user by non-admin user token
    - updateUserSelf (Fix PR [#4506](https://github.com/microsoft/pai/pull/4506))
      - [x] Update user self, patch: true
      - [x] Update user self, patch: false
      - [x] Update user self with incorrect username
    - deleteUser
      - [x] Delete a user
      - [x] Delete a non-existent user
      - [x] Delete a user by application token
      - [x] Delete a user by non-admin user token
    - updateUserGroup
      - [x] Add a group to a user's grouplist
      - [x] Add a group to a non-existent user's grouplist
      - [x] Add a group to a user's grouplist by application token
      - [x] Add a group to a user's grouplist by non-admin user token
    - deleteUserGroup
      - [x] Remove a group to a user's grouplist
      - [x] Remove a group to a non-existent user's grouplist
      - [x] Remove a group to a user's grouplist by application token
      - [x] Remove a group to a user's grouplist by non-admin user token
    - updateUserGrouplist
      - [x] Replace a user's grouplist
      - [x] Replace a non-existent user's grouplist
      - [x] Replace a user's grouplist by application token
      - [x] Replace a user's grouplist by non-admin user token
  
  - Error response handle:
  
    authn:
    - [x] IncorrectPasswordError (Fix PR [#4509](https://github.com/microsoft/pai/pull/4509))
  
    user:
    - [x] NoUserError
    - [x] UnauthorizedUserError
    - [x] ForbiddenUserError
    - [x] ConflictUserError
  
    job:
    - [x] NoJobError
  
    job history:
    - [x] NotHealthyError

    other:
    - [x] UnknownError (500, 502)

### Test CLI

  - [x] list clusters
  - [x] add cluster
  - [x] delete cluster
  - [x] list jobs
  - [x] submit job
  - [x] get job details
  - [x] ssh to the job container
  - [x] list storages
