### ISSUE TITLE
2020 June~July Release

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#4575]
This plan captures the work in June 2020. This is a 6 week iteration major focus on system features and improvements, and we will **ship** it in the beginning of **July**. 
 
We'll continue work we started in the previous iteration, and we started to pick up items from our [roadmap](https://github.com/Microsoft/pai/wiki/Roadmap).

## Release Manager
@Binyang2014 

## Endgame
Code freeze: 7.3
Scrum demo date: 7.9
Endgame & retrospective date: 7.20

## Plan Items
Below is a summary of the top level plan items.
- [x] UI improvement to support end2end marketplace needs, i.e. COVID-19 research site; AI EDU market, etc. @debuggy 
@yangou1988 @TobeyQin  (TODO: @debuggy book a prototype review on 6/28) 2 weeks for dev #4671 TestOwner @TobeyQin @qfyin 
- [x] Set up latency benchmark report for 100 virtual nodes --> 1500 virtual nodes * 8 job @ydye almost done, wait for automation script. Based on ansible. TestOwner: @Binyang2014 
    - [x] configuration generated role. (virtual-kubelet + openpai + ssl cert)
    - [x] Environment setup role. (virtual-kubelet + openpai + locust)
    - ~~[ ] Auto stress test script and stress test role. (locust)~~
- [X] GPU Fairness Usage (user gpu usage script improvement) @Binyang2014  #4266
- [X] Storage management experience: i.e. read only storage @abuccts TestOwner: @hzy46 #4688
- [X] disable http, use https instead @abuccts  TestOwner: @yiyione  TestDone
- [X] resolve always retry for port conflict: #4384 @Binyang2014 TestOwner: @abuccts TestDone
- [x] Support nested AD group in AAD Mode #3440 @ydye TestOwner: @scarlett2018 TestDone
     - [x] Code
     - [x] Test

## Engineering Improvements
- Engineering Excellent
  - [x] Add SDK to rest-server CI @yiyione PR: #4631
  - [x] SDK api tests in Azure Pipelines (e.g. [int bed tests](https://openpai.visualstudio.com/PAIexp/_build/results?buildId=622&view=ms.vss-test-web.build-test-results-tab))
  - [x] Webportal/VScode use SDK + SDK improvement @yiyione
      - [x] submit-job-v2 plugin (clone & submit jobs) PR: #4613 TestOwner: @debuggy 
      - [x] webportal job related API TestOwner: @debuggy 
      - [x] Storage API in webportal  TestOwner: @hzy46 TestDone
          - [x] JS SDK update. [PR](https://github.com/microsoft/openpaisdk/pull/42)
          - [x] Webportal update. PR: #4660
      - [x] VSCode convert old SDK code into 0.1.0 [PR](https://github.com/microsoft/openpaivscode/pull/13) TestOwner: @yiyione @qfyin 
  - [ ] Code coverage @abuccts
      - [x] Delete yarn code #4635 
  - [x] VSCode  code coverage  @yiyione 
      - [x] Add coverage report to CI
  - [x] JS SDK code coverage @yiyione 
      - [x] Add coverage report to CI [PR](https://github.com/microsoft/openpaisdk/pull/39)
      - [x] Add more tests

## Bug fixes
- [x] Align webportal submit defaulting with backend defaulting. Resolves #4691 TestOwner: @yqwang-ms TestDone
- [X] For tensorboard v2 the logdir is not right #4618 TestOwner: @hzy46 TestDone
- [x] Jobs mounted to the same AzureBlob cannot run in the same host #4637 @abuccts TestOwner: @Binyang2014 TestDone
- [x] Ssh barrier bug fix @Binyang2014 TestOwner: @abuccts TestDone
- [x] WebPortal submit job help link broken. Resolves #4690
- [ ] When job/task not completed, its completion time on WebPortal and RestServer is 0 (1970/1/1), confusing #4711 

## Doc
 - [x] Doc enhance Issue #4686 PR #4700

--------------
## Pending Items (moved to next iteration)
- [ ] The defaulting should only be done after submission phase #4576 @debuggy
- [ ] Surfacing more backend error to users in Job Details Page (@qfyin ,@yqwang-ms) #4649
   - [X] @yqwang-ms listed of the top potential error in OneNote
   - [X] Show "More Diagnostics" in job detail page  #4667 #4670  @debuggy TestOwner: @yqwang-ms  TestDone
   - [ ] Also show "More Diagnostics" in job retry history page #4689 @debuggy
   - [ ] Move "More Diagnostics" button to job level and disable its scroll button #4676 @debuggy
   - [ ] Show events in job detail and history page #4649 @debuggy
   - [ ] list out the potential scenario and possible display experience (i.e. advanced diagnostic mode) @debuggy
- [ ] Quick start for Azure, and deploy CNI issue @ydye 
- [ ] GPU Utilization improve training cost ROI for EDU scenario @hzy46 (**TODO**: book a scenario vs. design meeting) #4623
- [ ] Webportal use new storage API (thru SDK) + support DShuttle type @qfyin /@yiyione #4605 
- [ ] DShuttle integration and internal deploy & usage @Binyang2014 (depending on the above item; **TODO**: book an end 2 end user experience review meeting) #4599 
- [ ] New RestServer Arch: RestServer -> DB -> ApiServer @hzy46 /@yqwang-ms #4651 
- open bugs: https://github.com/microsoft/pai/labels/bug

## Deferred Items
N/A
