### ISSUE TITLE
2020 July ~ Aug Test Plan

### ISSUE THREAD

**Issue by yiyione** [microsoft/pai#4838]
**Target release date**: 
- Internal NE cluster deployment and flight target date: 9/15
- Official public date: 9/17

The test plan for 2020 July ~ Aug Release #4642

## Test Items

1. [x] DB migration #4651 (New RestServer Arch: RestServer -> DB -> ApiServer) FeatureOwner: @hzy46 TestOwner: @debuggy
    Stress test & failure test case #4818; Job list paging test cases: #4843

2. [x] VC && Group experience for Admin FeatureOwner: @yiyione TestOwner: @fanyangCS

3. [x] Error message for SKU (i.e. CPU only job errors) FeatureOwner: @abuccts TestOwner: @debuggy 
   #4847 

4. [x] Robustness improvement features #4694 FeatureOwner: @Binyang2014 TestOwner: @abuccts 

5. [x] HiveD improvement FeatureOwner: @abuccts TestOwner: @yiyione 
    test cases: 1. [`gangAllocation: true`](https://github.com/microsoft/hivedscheduler/blob/master/example/feature/README.md#basic) 2. [`gangAllocation: false`](https://github.com/microsoft/hivedscheduler/blob/master/example/feature/README.md#opportunistic-job) 3. [`lazyPreemptionEnable: true`](https://github.com/microsoft/hivedscheduler/blob/master/example/feature/README.md#lazy-preemption) 4. [GPU id](https://github.com/microsoft/hivedscheduler/blob/master/example/feature/README.md#topology-aware-intra-vc-scheduling)

6. [x] Marketplace features FeatureOwner: @debuggy  TestOwner: @TobeyQin [test cases](https://github.com/microsoft/openpaimarketplace/issues/54)

7. [x] Webportal api/v1 code update FeatureOwner: @yiyione TestOwner: @debuggy
Test cases: 1. View tokens in user's profile page. 2. View services in admin page. 3. View k8s dashboard in admin page.

8. [x] Runtime image [check issue](https://github.com/microsoft/openpai-runtime/issues/17) FeatureOwner: @Binyang2014 TestOwner: @hzy46 [test cases](https://github.com/microsoft/openpai-runtime/pull/20#issuecomment-681568880)

10. [x] REST server history and detail page code refactor #4823 FeatureOwner: @debuggy TestOwner: @yiyione 

## Known bugs during the tests

- [x] Some job retry attempts missing on AKS #4877

- [x] additional fields regression in HiveD config (Fix PR: #4878)

- [x] Resource in job config will be changed after uploading to webportal #4881  

- [x] Cannot launch job because of BarrierNotPassed #4833

- [x] HiveDScheduler image will not update if use same tag, e.g. tag:int (fix PR: #4837)

- [x] Memory issues for framework watcher and poller in DBController (track in Issue #4850 ;mitigate in PR #4845 by increasing memory limit and adding concurrency control)

- [x] Database poller will be dead locked when 30000+ concurrent RPC calls happen (track in issue  #4849; mitigate in PR #4845 by increasing memory limit and adding concurrency control)

- [x] Job list page will show ”no results matched your search“ before show job list (fix PR: #4839)

- [x] Failed to create Pod: couldn't get version/kind; json parse error: unexpected end of JSON input (\u003cempty\u003e) #4840

- [x] Pod Node didn't have enough resource #4841

- [x] Job list page didn't refresh or show loading page immediately after filter update. (fix PR: #4842)

- [x] Job list page didn't refresh after sort by column. (fix PR: #4844)

- [x] `order` parameter in list job API not working. (fix PR: #4844)

- [x] Job retry history error: Cannot generate proper exit diagnostics when too much storage is used #4769 #4867 (Fix PR: #4867)

- [x] Cannot view retry history of jobs with large task number and large retry times #4846 (Fix PR: #4870)

- [x] Cannot view full vc chart on laptop

- [x] List jobs API with vc order will get 500 Error "column framework.vc does not exist" (Fix PR: #4851)

- [x] Job list page, If the order has something wrong, user could not resume the original state unless delete the localstorage #4852.  (Fix PR: #4854, #4861)

- [x] Job list page, set a filter & click the refresh button, will not get the filtered result. (Fix PR: #4854)

- [x] Job state inconsistent in list and detail page

- [ ] Task retry will cause wrong framework retry records #4911
