### ISSUE TITLE
2020 Sept ~ Oct release plan

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#4898]
This plan captures the work in Sept 2020. This is a 6 week iteration major focus on system features and improvements, and we will ship it in the beginning of August.

## Release Manager
@abuccts 

## Endgame
Feature freeze: 9/30
Code freeze: 10/15
Scrum demo date: 9/30 ~ 10/12
Endgame & retrospective date: tbd

## Plan Items
Below is a summary of the top level plan items.
### marketplace related items microsoft/openpaimarketplace#60
- [x] Grammar check @debuggy 
- [x] Fix data storage config   mismathcing issue @debuggy
- [x] COVID 19 bug fix @debuggy
- [x] X-Ray Chest Check @yiyione
- [x] Distributed Job @hzy46 

test owner: @TobeyQin 

### HiveD scheduler
- [x] Cluster autoscaler with HiveD scheduler on aks. @abuccts #4868 
- [x] Support dynamic sku types for different vc on webportal @abuccts #4900 

test owner: @yiyione 
- [x] test case: on submission page, choose one vc, check sku type dropdown list, change another vc, check if dropdown list changes.

### advanced job debug mode:
Per Task Retry History:
- [x] FC generates Task history snapshots https://github.com/microsoft/frameworkcontroller/pull/62 @yqwang-ms
- [x] Fluentd + DB to collect above snapshots @hzy46
- [x] RestServer enrich job detail API by supporting history job attempt and including history task attempts @suiguoxin
- [x] WebPortal expose the Per Task Retry History @debuggy #4966 
- [x] FC release and update PAI @yqwang-ms

test owner: @yqwang-ms 
Issues:
- [x] View Exit Diagnostics misplaced
- [x] when switch job attempt, table content and more diag button is unmatched
- [ ] After click stop button sucessfully, the button is still enabled until the job becomes Stopping https://github.com/microsoft/pai/issues/5023

Expose K8s events:
- [x] event watcher to support #4649 @hzy46   PR: #4939 
- [x] add event api @hzy46
- [x] show events in job detail page @debuggy #4975 

Test cases in PR #4939
test owner: @abuccts 

### GPU monitoring and utilization
- [x] GPU utilization monitoring & handling #4789 @suiguoxin 

test cases: cordon-nodes / send email to user and admin / tag job 
test owner: @Binyang2014 

### DShuttle 
- [x] Webportal support DShuttle type @yiyione #4605 
- [x] DShuttle integration and internal deploy & usage @Binyang2014 (depending on the above item; ) #4599  #4584 

test case: 
1. Upload data into AzureBlob which connected to DShuttle.
2. Submit job which mount DShuttle.
3. Consume the data through DShuttle mounted path

For failure pattern, please refer to https://github.com/microsoft/pai/issues/4599#issue-629645451 

### Documentation
- [x] Use PAI DRI notebook, DRI tickets and Wiki to update document @hzy46 #4760 #1763 PR: #4828 #4821
- [x] Component owner brownbag plan @scarlett2018 

### Web Portal Experience
- [x] Add help info for items in submit job page @debuggy #4950
- [x] User experience survey

test owner: @hzy46 

-----------
Other Candidates

_postponed from last release_
- [x] GPU Utilization improve training cost ROI for EDU scenario @hzy46  #4623
- [x] 22. Following up items of DB
   - [x] P1 archive (delete) jobs (SHAIIC) #4453 @suiguoxin 
   - [x] P2 Job tags (SHAIIC) @suiguoxin 
   - [comments] DB replication; Master/Slave; SQL Azure; Recover method; P2 //(pending)job GC 

test owner: @debuggy 
test cases: Job tags: add / delete tag api
- [x] #5009

### Backlog
Moving to #4988
