### ISSUE TITLE
Group & VC request management for user and admin

### ISSUE THREAD

**Issue by yiyione** [microsoft/pai#4949]
## Motivation

Providing an easy way to manage user's VC requests on webportal.
Resources like VC and teamwise-storage are binding to `Group` in OpenPAI, when a user request a VC or storage, the admin need to figure out which groups to join.
And we don't have a group management UI in webportal.

### Users can submit their request on OpenPAI

User can submit requests (user sign up, VC permission, Storage permission) on webportal/rest-API.
Admin can view the user's requests on webportal, and the UI can help Admin to figure out which groups the user can join or create a new account for the user (basic mode).

Note: user's requests will be stored in ETCD (As the group info was in there).

### Group management page for Admin

Add a group management page in webportal for Admin.

## Work Items

- [ ] Add new API in rest-server for the requests #4948.
- [ ] Add sign up and user request pending list page.
- [ ] Add vc request and vc request pending list page.
- [ ] Add group management page.

## UI Design

![signup](https://user-images.githubusercontent.com/17357108/95689355-c22c7380-0c42-11eb-8790-404cc0ade67b.png)
![requestVC](https://user-images.githubusercontent.com/17357108/95689357-c6f12780-0c42-11eb-8933-dcf27b10917b.png)
![requestVC2](https://user-images.githubusercontent.com/17357108/95689358-c9ec1800-0c42-11eb-8755-809cf95c6c3d.png)
![pendinglist](https://user-images.githubusercontent.com/17357108/95689360-cc4e7200-0c42-11eb-9c91-42f85831fb10.png)
![groupSelection](https://user-images.githubusercontent.com/17357108/95689807-fa818100-0c45-11eb-8dde-e1d39ac22a2e.png)
