### ISSUE TITLE
2020 Oct ~ Nov release plan

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#4988]
This plan captures the work in Nov 2020. This is a 4 week iteration major focus on system features and improvements, and we will ship it at the end of Nov.

## Release Manager
@suiguoxin 

## Endgame
Feature freeze: **TBD**
Code freeze: 11.16
Scrum demo date: TBD
Release date & retrospective date: 11.30

INT bed deploy date: 11.17
Bug bash: #5087

-------------
#### multi-cluster
- [x] P0 - Hybrid or multi-cluster management (SHAIIC) #4929 @hzy46  ETA: **11.9** demo: 11.5 

#### Autoscaler 
-  [x] P2 doc refine @abuccts #5057  ETA: **11/6** in review

#### Log Collection 
- [x]  P1 Log collection #4992
    - [x] API   @Binyang2014
    - [x] Front-end @AmberMsy  
       - [x] update API logic for  `Stdout` / `Stderr` / `Sdtout+Stderr` button ETA: 11/11
       - [x] update `Browse log folder`  ETA **11/16** 

#### Https related issues 
- [x] P2 doc **ETA: 11/11** @vvfreesoul 

#### [Marketplace](https://github.com/microsoft/openpaimarketplace/issues/73)
- Data -- @debuggy
- [x] P0 Move NFS to Azure Blob as backend -- ETA: Nov. 5
- [x] P0 Upload Job output to Azure Blob ETA: 11.9
- [x] P0 Download data from azure blob to local -- ETA: Nov. 9
- [x] P1 Use Azure storage SDK for privacy -- ETA: 11.16
- [x] P1 Refactor data use logic after change storage to blob ETA: 11.13
- Service Deployment -- @yiyione
- [x] P0 Start Local Rest Server -- ETA: Nov. 2   
- [x] P0 Deployed Rest Server in PAI -- ETA: Nov. 5
- [x] P0 Start database and save items into it ETA: 11.9
- [x] P0 Register in PAI pylon PR: #5066 -- ETA: Nov. 10 PR review
- [x] P0 Create marketplace item -- ETA: Nov. 16

#### Web Portal Experience
- [x] P0 After click stop button successfully, the button is still enabled until the job becomes Stopping #5023 @debuggy  ETA: 11/16 #5079 in review

#### Admin Experience
- [x] P1 Alert rules update: https://github.com/microsoft/pai/issues/4810 @suiguoxin  #5021 ETA: 11/10
- [x] P2 Deployment issues #5001 @suiguoxin ETA: 11/15 #5077 #5085 

#### Bug Fix
- [x] Admin auth check issue in APIs: getGroupUserList, createGroup, creatUser, updateUserGroupList @suiguoxin #5032 #5051
- [x] `updateUserGroupList` not work @suiguoxin #5121 
- [x] hived config issue caused by k8s coreDNS deployment #5056  @Binyang2014 @hzy46  #5071
- [x] Forever running job caused by out of sync between api server and database #5065 DRI handbook doc @hzy46  
    - Updated DRI handbook (in the `Etcd Maintainence` page) 

#### Web Portal Experience
- [ ] P2 Job detail, task list : sort, filter, search, export csv @yiyione 
- [ ] P1 Job detail page cannot be searched by browser #4917 @debuggy  defer can be solved with sort/filter
- [ ] P3 weportal overlap issue #5086 

#### Admin Experience
- [ ] P2 Group management & VC request management for user and admin @yiyione #4949 ETA: defer

#### VS Code
- [ ] [P3 bug fix](https://github.com/microsoft/openpaivscode/issues?q=is%3Aissue+is%3Aopen+label%3Abug) @yiyione ETA: defer

#### HiveD scheduler  
- [ ] P2 Cell as sku in hived scheduler. @abuccts (backbone support (config) for "Cell", submission form supports for Cell)
ETA: design: **in progress** 

- [ ] P2 Python 2 Deprecation #5042 
#### Release Tracking 
- [ ] Release Process: refine archived oneNote doc as github wiki @yiyione 
- [ ] Deployment: doc for release branch deployment @yiyione 

### Rest Server Performance
- [ ] Rest-Server Job API Perf Tests and Improvements https://github.com/microsoft/pai/issues/5027

#### Web Portal Experience
- [ ] P2 Favorite jobs (SHAIIC) @suiguoxin 

#### Submission Related Backlog
- [ ] P1 The defaulting should only be done after submission phase #4576 @debuggy ETA: TODO after 11/6
- [ ] P2 Submit job ui should show protocol prerequisites parts https://github.com/microsoft/openpaimarketplace/issues/73 @debuggy  @yiyione @TobeyQin
