### ISSUE TITLE
V1.4 Bug Bash

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/pai#5087]
## Endgame
- INT deploy: 11/18
- Target Test Duration: 11/17 ~ 11/30

upgrade plan
- ne/rr: 12/2
- wu2: 12/9

-------------
#### multi-cluster
- [x] P0 - Hybrid or multi-cluster management (SHAIIC) #4929 @hzy46 
test owner: @yiyione @debuggy ( test in int/32 bed)
test cases: https://github.com/microsoft/pai/pull/5082#issuecomment-727752606
issues: #5118 

- [x] #### Hived CPU #5075 
test owner: @hzy46 
test cases: use [this config](https://github.com/microsoft/pai/pull/5075/files?short_path=dc96cca#diff-dc96cca98054bc7ca288d3f2526209c7ff4dcef251dd233ef7c346e899a4e125) then submit cpu and gpu jobs on same node

#### Log Collection 
- [x]  P1 Log collection #4992
    - [x] API   @Binyang2014
    - [x] Front-end @AmberMsy  
       - [x] update API logic for  `Stdout` / `Stderr` / `Sdtout+Stderr` button 
       - [x] update `Browse log folder` 

test owner: @abuccts 
test cases:
- Run command which will write disk heavily
- Test log url will be expired after 2 mins
- Click `Stdout`/`Stderr`/`Stdout+Stderr` button to get the corresponding log.
- Click `Stdout`/`Stderr`/`Stdout+Stderr` button and wait for 2 mins, the log content can still be displayed.
- When the current `log` file is less than 15K and there is a `log.1` file, it will merge `log` and `log.1` files and display the last 16K content. (`log` here refers to `Stdout`, `Stderr`, etc.)
- Click the `Show All Logs` button. A Dialog box will pop up, linking to all logs.

- Input invalid log name, should return 400
- Show all logs should download log file, Check open huge log file will not block frontend 
known issues:
- [x] show all logs crash #5119
- [x] show all logs crash (webportal) #5122  
- [x] all task retry logs 
ETA: 11.27

##### Data @debuggy
- [x] P0 Move NFS to Azure Blob as backend -- ETA: Nov. 5
- [x] P0 Upload Job output to Azure Blob ETA: 11.9
- [x] P0 Download data from azure blob to local -- ETA: Nov. 9
- [x] P1 Use Azure storage SDK for privacy -- ETA: 11.13
- [x] P1 Refactor data use logic after change storage to blob ETA: 11.13
test owner: @TobeyQin  @mingliang's intern
test cases:
   - [x] Webpage layout and items display correctly.
   - [x] All the link and button works.
   - [x] Test data download
   - [x] Test Create template logic and if it can successfully add template.
   - [x] Test Azure storage URL is correct and accessible.
   - [x] Test if all the jobs can finish successfully.
   - [x] Test if can get output files when job finished.
known issues:
   1. - [x] Failed to fetch job log (#5094 )
   2. - [x] Error no available connection strings [Marketplace #104](https://github.com/microsoft/openpaimarketplace/issues/104) PR in review
   3. - [x] Cannot read property 'commands' of undefined [Marketplace #105] (https://github.com/microsoft/openpaimarketplace/issues/105) PR in review
   4. - [x] covid chestxray dataset job failed[Marketplace #106](https://github.com/microsoft/openpaimarketplace/issues/106) 
- [x] #112, 113,117,118
ETA: 11.27

 
##### Service Deployment -- @yiyione
- [x] P0 Start Local Rest Server -- ETA: Nov. 2   
- [x] P0 Deployed Rest Server in PAI -- ETA: Nov. 5
- [x] P0 Start database and save items into it ETA: 11.9
- [x] P0 Register in PAI pylon PR: #5066 -- ETA: Nov. 10 PR review
- [x] P0 Create marketplace item -- ETA: Nov. 12
test owner: @debuggy @suiguoxin 
test cases: https://github.com/microsoft/pai/pull/5066#issuecomment-729334425

#### Web Portal Experience
- [x] P0 Job detail page cannot be searched by browser #4917 @debuggy  ETA: 11/16 needs confirm
- [x] P0 After click stop button successfully, the button is still enabled until the job becomes Stopping #5023 @debuggy  ETA: 11/16 #5079 in review
test owner: @yqwang-ms 
test cases: 

#### Admin Experience
- [x] P1 Alert rules update: https://github.com/microsoft/pai/issues/4810 @suiguoxin  #5021
test owner: @Binyang2014 
test cases: 
- alert inhibition : PaiServicePodNotRunning / PaiServicePodNotRunning should not be fired when NodeNotReady is already fired
- alert severity render
- alert email templates: customized templates, kill-user-job-alert template render;

- [x] P2 Deployment issues #5001 @suiguoxin
test owner: @hzy46 
test cases: 
- deploy with master branch code & self-built dev-box image with dockerfile from master branch

#### Bug Fix
- [x] Admin auth check issue in APIs: getGroupUserList, createGroup, creatUser, updateUserGroupList @suiguoxin
test owner: @abuccts 
test cases:
- getGoupUserList (get /api/v2/group/:groupname/userlist): 
    - test in AAD or basic AUTH mode
    - the response of the API with admin / non-admin token (200 / 401)
- createGroup (post /api/v2/group) :
    - test in AAD or basic AUTH mode 
    - the response of the API with admin / non-admin token (201 / 403)
    - use getGroup (Get /api/v2/group/:groupname) API to check if the group is created  (should not be created with non-admin token)
- createUser (post /api/v2/users):
    - test in basic AUTH mode
    - the response of the API with admin / non-admin token
    - use getUser (Get /api/v2/users/:username) API to check if the user is created
- updateUserGroupList (put /api/v2/users/:username/grouplist)
    - test in basic AUTH mode
    - the response of the API with admin / non-admin token
    - use getUser (Get /api/v2/users/:username) API to check if the user group list is updated (should not be updated with non-admin token)

issues:
- [x] #5120 

- [x] hived config issue caused by k8s coreDNS deployment #5056  @Binyang2014 @hzy46 PR: #5071
test owner: @suiguoxin 
test cases:
-
