### ISSUE TITLE
2021 Jan release plan

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#5141]
This plan captures the work in Jan 2021. This is a 6 week iteration major focus on system features and improvements, and we will ship it at _**to-be-decided**_.

## Release Manager
@debuggy

## Endgame
Feature freeze: Dec. 24
Code freeze: ~Dec. 21~ Dec. 24
Scrum demo date: Dec.24
Bug Bash date: Dec.28 ~ Jan. 8
Release date & retrospective date: **TBD**

### Web Portal Experience test owner: @suiguoxin 
- [x] Responsive UI for surface book or other mobile device @debuggy @yangou1988 test: @TobeyQin 
   [responsive design principles](https://github.com/microsoft/pai/wiki/Responsive-Design-Principles)
- [x] P0 Home page overlap issue #5086 #5180 @debuggy test: @suiguoxin  test cases: Issues: #5086
- [x] P0 Job detail page. Test cases: https://github.com/microsoft/pai/pull/5175#issuecomment-745846576 @suiguoxin 
  - [x] Add sort, filter and search in task detail list #4917 @yiyione ETA: 12/14
  - [x] Add export csv function @yiyione  ETA: 12/14
- [x] Job Submission page test: @suiguoxin @TobeyQin 
  - [x] P1 The defaulting should only be done after submission phase #4576 #5172  @debuggy ETA: Dec. 22 Demo: Dec. 24
  - [x] P1 New Job Submission Page Design  @yangou1988  @debuggy ETA: Dec. 22 Demo: Dec. 24

### Support different types of computing hardware #5138 @mydmdm  test owner: @abuccts  [test cases](https://github.com/microsoft/pai/issues/5138#issuecomment-750807049)  suiyuan
- [x] add support to enflame DTO #5140
 
### Deployment process refinement @suiguoxin @hzy46 
- [x] P0 Installation entry point: ETA: 3 days
    - [x] `master.csv` + `worker.csv` -> `layout.yaml` 
    - [x] move `config.yaml`, `layout.yaml` under quick-start folder, remove all the argument parse logic
    - [x] doc refactor 
    - [x] `layout.yaml` schema change
- [x] P0 unify version requirements: pai version, pai image tag ETA: 1 day
    - [x] set default value in config files
    - [x] create a wiki for release manager : [wiki](https://github.com/microsoft/pai/wiki/How-to-Create-a-PR-for-New-Release)
- [x] add / remove node 
    - [x] P0 fix current remove-node doc: do not work
- [x] P1 generate hiveD config with `layout.yaml` ETA: 3 days #5179 
    - [x] generate one `vc` for every `machine-sku`, leave the first vc as default vc
    - [x] calculate free resources with specification in `layout.yaml`
- [x] P1 check layout before installing k8s: ETA: 3 days
    - [x] one-master constraint, master-node / worker-node can not be in the same machine #5184    
    - [x] resource requirements, support CPU / provide interfaces for other computing devices #5181
- [x] P1 config folder structure arrangement
- [x] P1 Refine installation logs: ETA: 1 day
    - [x] add log for key steps
    - [x] remove verbose & useless log
- [x] P1 add skip service list argument #5193

test owner: @debuggy @hzy46 
Test Cases:
- deploy from scratch: follow [doc](https://github.com/microsoft/pai/blob/master/docs/manual/cluster-admin/installation-guide.md#installation-from-scratch) @debuggy @TobeyQin 
    - pure CPU cluster
    - CPU / GPU mixed cluster
    -  pure GPU cluster
- upgrade from v1.4.1 to v1.5.0 [doc](https://github.com/microsoft/pai/blob/master/docs/manual/cluster-admin/upgrade-guide.md) @debuggy #5208 
    - test `skip-service-list` argument    
- add / remove nodes : [doc](https://github.com/microsoft/pai/blob/master/docs/manual/cluster-admin/how-to-add-and-remove-nodes.md)
- uninstallation: [doc](https://github.com/microsoft/pai/blob/master/docs/manual/cluster-admin/how-to-uninstall-openpai.md)

### Log manager test owner: @yiyione 
- [x] P1 get logs api return code #5125 @Binyang2014  ETA: dec. 18

### Release Tracking test owner: @debuggy 
- [x] feature proposal issue template including motivate and test cases @debuggy
- [x] P1 Deployment: doc for release branch deployment @suiguoxin 

### Dockerhub pull policy #5219 
- [ ] Docker image pull frequency limit in dockerhub @qiufeng  large job test
Possible Solutions:
  - **use Microsoft account**; waiting for reply
  - docker image in China;
  - docker hub pro;

### Backlog
- [ ] Rest-Server Job API Perf Tests and Improvements https://github.com/microsoft/pai/issues/5027
- [ ] Python 2/3.5 Deprecation #5042
- [ ] P1 add / remove node with with `layout.yaml` #5167 
- [ ] P2 dev-box can be inside master node: doc, testing
- [ ] Refine Alert System #4810 P2 items
- [ ] P2 too many tokens created https://github.com/microsoft/pai/issues/5123
- [ ] P2 Group management & VC request management for user and admin @yiyione #4949
- [ ] P2 [vscode bug](https://github.com/microsoft/openpaivscode/issues?q=is%3Aissue+is%3Aopen+label%3Abug) @yiyione
- [ ] P1 (design) Submit job ui should show protocol prerequisites parts https://github.com/microsoft/openpaimarketplace/issues/73 @debuggy  @yiyione @TobeyQin 
- [ ] P2 code coverage concern when developing feature
- [ ] P1 Release Process: refine archived oneNote doc as github wiki @yiyione
- [ ] P1 Agile CI and split heavy tests with nightly-deployment #5173 @yiyione
    - [ ] Design how to split the CI
    - [ ] Setup the nightly-deployment and test
 
### HiveD scheduler  
- [ ] Cell as sku in hived scheduler. @abuccts (backbone support (config) for "Cell", submission form supports for Cell)
ETA: design: **in progress** 
- [ ] P2 UX for HiveD @yangou1988 

### Job protocol update
- [ ] P1 support data via extending `prerequisite` in job protocol #5145

### DB controller
- [ ] make DBController tolerant to wrong framework request #4889 #5093
