### ISSUE TITLE
generate an application token for every job

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/pai#5270]
### Motivation
- enable runtime plugins to access rest-server

### Design
- Background: currently, all user tokens are saved in the same k8s secret in namespace 'pai-user-token', in `data` field
-  save `job-specific` tokens in another namespace named 'pai-job-token', **one secret for one user**
- do not return `job-specific` tokens in get tokens API by default
- verify tokens: check both normal tokens & job-specific tokens
- revoke job-specific tokens :
   - in database-controller, when jobs finished
   - in rest-server, `purge()` function, each time when `list()` / `verify()` is called

#### API change
- revoke tokens: 
  - revoke self: no constraint
  - else: not application_token

#### Schema of the job-specific secrets:
```yaml
apiVersion: v1
data:
  encode(frameworkName): token
kind: Secret
metadata:
  creationTimestamp: "2021-01-18T01:52:22Z"
  name: username
  namespace: **pai-job-token**
  resourceVersion: "10515250"
  selfLink: /api/v1/namespaces/pai-job-token/secrets/hash(username)
  uid: 72658f49-d620-45c5-ab07-e5fd0a14acb9
type: Opaque
```

### Work Items
- [x] create application token in rest-server, get a k8s secret definition #5282
- [x] create a token object in db, (add a column in table Framework named tokenSecretDef...), let dbc create the secret with the def #5282
- [x] revoke the token in dbc, (remove the token from DB) : realized in src/dbc #5282
- [x] filter/hide token in webportal/rest-server in user-profile page
    - save the secret in a different namespace, return only user-tokens by default #5292
- [x] revoke the job tokens after jobs finished
    - [x] in purge() function #5292

**Comment by suiguoxin** [comment]
Change:

## Issues of the approach above:
- Save job-specific token in k8s secrets leads to more complicated purge() & verify() operation, which is of O(n) time complexity.

## New design
### sign 
sign a token with the following payload schema:
``` 
{
    username,
    application,
    jobSpecific, // indicate if the token if for a specific job only
    frameworkName, 
}
```
- no need to save the token in 

### verify
for job specific token verification:
- vefiry with jwt
- check if the job has completed
- no need to check k8s secret data

### purge
no need to purge job-specific tokens since they are not saved
