### ISSUE TITLE
2021 Feb Endgame Plan

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#5319]
release plan #5253 
release manager @hzy46
test period: TBD

## New Feature

Feature | Feature Owner | Test Owner(s) | Test case
- [x] Job submission page new UI | @debuggy | @yiyione |   https://github.com/microsoft/openpaimarketplace/issues/206
- [x] Job protocol update: add prerequistes | @hzy46 | @suiguoxin @Binyang2014  | [test cases](https://github.com/microsoft/pai/issues/5145#issuecomment-769765210)
- [x] Marketplace https://github.com/microsoft/openpaimarketplace/issues/225
- [x] Dockerhub cache | @debuggy | @Starmys | test case TBD
- [x] GPU Utilization Statistics | @suiguoxin | @Binyang2014 |
    - Test cases: 
        - set alert schedule in services-configuration.yaml->alert-manager->cluster-utilization->schedule
        - check the email report
- [x] save SSH publish keys on user profile page | @Lijiaoa @suiguoxin | @hzy46 
    - Test cases:
        - in webportal, check add / delete /view ssh public key functions
        - submit job with ssh enabled, add some secret key/value (to test that they have no conflict)
        - `kubectl get secrets | grep usercred`, a corresponding secrets should be created in default namespace
        - both pre-saved key & new key should work 
        -  
- [x] Log experience | @Binyang2014 | @hzy46 |
- [x] Reduce ansible logs when deploy #5305 | @Starmys @suiguoxin | @hzy46 

## Bug Fixes
- [x] DB controller | @hzy46 | @debuggy |
    - [x] Tolerant to wrong framework spec #5284 
    - [x] Remove sensitive fields in db #5289
    - [x] Fix memory leak #5309
- [x] Set correct launchTime in rest-server #5307 | @suiguoxin | @Binyang2014 
Test cases: 
- call API https://int.openpai.org/rest-server/api/v2/jobs/{frameworkName}
- check jobStatus->appLaunchedTime filed
- check job in different status (waiting/ running / completed)

## Regression Test
(as usual)

### Found Issues
- [x] Database may use unmounted host path #5341
- [ ] K8s API server's cert need renew each year #5334
- [x] Fix wrong nvidia gpu card number #5353
- [ ] Fix get-pip.py compatibility problem with Python3.5 #5356

### Agile CI and nightly-build
 P1 Agile CI and split heavy tests with nightly-deployment #5173 @yiyione
- [x] Setup the nightly-deployment and test
- [x] Build & publish nightly tag image
- [ ] Add build failure alert to contributor
- [ ] Replace current Jenkins CI

### Document
- [ ] fault document @mydmdm
- [x] update add&remove  node doc @suiguoxin 
- [x] update aad doc @suiguoxin 
- [ ] **document for new features**
    - [ ] docker image cache
    - [x] save user's SSH keys
    - [x] GPU Utilization Statistics
    - [x] Job protocol update: add prerequistes
