### ISSUE TITLE
Inform the user when job fails

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/pai#5337]
## Motivation
Some jobs may fail unexpectedly. 
If the users can be informed when the jobs fail, the users will be able to handle the issue in time.
This will save the users from checking their job status all the time.

## Design
- enable this feature in job protocal
```yaml
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
  hivedScheduler:
    taskRoles:
      taskrole:
        skuNum: 1
        skuType: GENERIC-WORKER
  **informAtFailure: true**
```

**Comment by fanyangCS** [comment]
the notification is also useful when the job succeed. maybe the feature could be rephrased as: notifying the user when a job completes.

**Comment by fanyangCS** [comment]
related to https://github.com/microsoft/pai/issues/2235 https://github.com/microsoft/pai/issues/3640

**Comment by suiguoxin** [comment]
## Work Items

### Part 1: Job / User configuration
* [ ] Job configuration
    - [ ] add a field in protocal: `extra -> informAtFailure` P0
        - [x] no need to update protocol since `extra`  is free object  
            - (webportal & rest-server schema validation: refer to #5277)
            - (protocal : refer to https://github.com/microsoft/openpai-protocol/pull/9/files)
        - [ ] parse the field when submit job
    - [ ]  webportal job submission page design P2

* [ ] User Configuration
    - [ ] add a field in user info `extra -> getJobStatusChangeNotificationBy` P1
    - [ ] webportal user profile page P2

* [ ] Filter alerts by users P1
   - [ ] add a Rest API #5407
   - [ ] webportal change: use REST API instead of alert-manager API

### Part 2: monitor & trigger corresponding alerts P0
- [ ] add the following columns to the `framework` table in DB to save job config & alerts state : P0
- [ ] add a container `framework-status-notification-poller` in `alert-manager`, which P0
    - watch DB `framework` table
    - send the alert when the config is enabled & the alert has not been sent
    - update `framework` table after successfully sending alerts to `alert-manager`

### Part 3: alerts handling P0
- [ ] `src/alert-manager/deploy/alert-manager-configmap.yaml`: add a new `receiver` and a new `route` 
- [ ] `alert-handler`: add an email template `inform-user-job-status-change`
