### ISSUE TITLE
2021 May Release Plan

### ISSUE THREAD

**Issue by yiyione** [microsoft/pai#5451]
## Release Manager
@yiyione 

## Endgame
Feature freeze: TBD
Code freeze:  2021.06.04
Scrum demo date: TBD
Bug Bash date: 2021.06.08
Release date & retrospective date: TBD

## Test Plan:
TBD

## Top level themes

* x-plan
* Marketplace backlog - @debuggy / @yiyione / @TobeyQin

   [Marketplace 2021 April Release Plan #278](https://github.com/microsoft/openpaimarketplace/issues/278) Test owner: @debuggy @TobeyQin
        - [] test

### Alert-Manager
- [x] send alert to user when job failed #5337 @suiguoxin P2 Test owner: @hzy46 
    - [x] Test

### Deployment
- [ ] v1.6.0 deployment issues @yiyione
    - [ ] ubuntu 16.04 deployment issue #5445
    - [x] #5468

### Others
- [x] Customizable Autoscaler #5412 @hzy46 @Starmys P1 Test owner: @yiyione
    - [x] test
- [x] Clean up repo. Remove obsolete code P1 @Binyang2014 
- [x] Priority in job list #5417 Test owner: @debuggy 
    - [x] test 

- [x] AAD msgraph API 400 error (log in failed)

### Use case & best practice
* Use case and best practice summary - @hzy46 / @TobeyQin / @suiguoxin 
   * OpenPAI Advantage
   * OpenPAI Best Practice -- P0 topics:
      - Cluster setup and onboarding
      - Utilization weekly report
      - Storage
      - How to debug
      - Leverage low-priority resources
      - AutoML
*  HiveD user experience support - tbd @yangou1988 VC view page(design review in this release) P1
* Dataset: integrate data prerequisite into marketplace and job submission page @hzy46 #5345 TBD P1

- [x] Add custom ssl port support. resolves #5386 #5387 @Binyang2014 #5495 test owner: @yiyione
    - [x] test 

defer
- [ ] investigate auto rotate the k8s cert #5439 @yiyione 
- [ ] Provide no cni mode #5436 P2
- [ ] LDAP P2
